import { supabase } from './supabase'

const FALLBACK_COLUMNS: Record<string, string[]> = {
  job_card_closed_data: [
    // System columns
    'id',
    'branch',
    'created_at',
    'updated_at',
    // Text columns
    'job_card_number',
    'sr_type',
    'chassis_number',
    'parent_product_line',
    'product_line',
    'first_name',
    'last_name',
    'sr_assigned_to',
    'vehicle_registration_number',
    'account_phone_number',
    'employee_code',
    // Numeric columns
    'final_labour_amount',
    'final_spares_amount',
    'total_invoice_amount',
    // Datetime/date columns
    'created_date_time',
    'closed_date_time',
    'vehicle_sale_date',
  ],
  service_invoice_data: [
    'invoice_number',
    'invoice_date',
    'bill_to_first_name',
    'bill_to_last_name',
    'final_labour_invoice_amount',
    'final_spares_invoice_amount',
    'final_consolidated_invoice_amount',
    'order_number',
    'sr_number',
    'chassis_number',
    'vrn',
    'branch',
  ],
  cancel_job_card: [
    'job_card_number',
    'status',
    'vehicle_registration_number',
    'job_card_channel',
    'created_date_time',
    'completed_date_time',
    'closed_date_time',
    'service_request_no',
    'account',
    'last_name',
    'first_name',
    'labour_rate_list',
    'sr_assigned_to',
    'parts_price_list',
    'customer_po_ref',
    'delivery_variance_percent',
    'sr_type',
    'payment_type',
    'fms',
    'insurance_company_name',
    'insurance_type',
    'insurance_expiry_date',
    'open_for_days',
    'parts_entry_complete',
    'crn',
    'action_on_delay_reason',
    'arn',
    'account_phone_number',
    'contact_phones',
    'vehicle_delivery_date',
    'effective_final_delivery_estimate_date',
    'delivery_variance_hours',
    'effective_total_estimate',
    'total_estimate_variance_percent',
    'balance_payment_to_be_adjusted',
    'total_payment_amount_adjusted',
    'parent_product_line',
    'product_line',
    'division',
    'total_invoice_amount',
    'kms',
    'hours',
    'vehicle_sale_date',
    'tm_invoice_date',
    'warranty',
    'amc',
    'final_labour_amount',
    'final_spares_amount',
    'total_order_value',
    'delay_reason',
    'jobs_entry_complete',
    'supervisor',
    'invoiced',
    'invoice_format',
    'chassis_number',
    'branch',
  ],
  closed_but_not_invoiced: [
    'job_card_number',
    'status',
    'vehicle_registration_number',
    'job_card_channel',
    'created_date_time',
    'completed_date_time',
    'closed_date_time',
    'service_request_no',
    'account',
    'last_name',
    'first_name',
    'labour_rate_list',
    'sr_assigned_to',
    'parts_price_list',
    'customer_po_ref',
    'delivery_variance_percent',
    'sr_type',
    'payment_type',
    'fms',
    'insurance_company_name',
    'insurance_type',
    'insurance_expiry_date',
    'open_for_days',
    'parts_entry_complete',
    'crn',
    'action_on_delay_reason',
    'arn',
    'account_phone_number',
    'contact_phones',
    'vehicle_delivery_date',
    'effective_final_delivery_estimate_date',
    'delivery_variance_hours',
    'effective_total_estimate',
    'total_estimate_variance_percent',
    'balance_payment_to_be_adjusted',
    'total_payment_amount_adjusted',
    'parent_product_line',
    'product_line',
    'division',
    'total_invoice_amount',
    'kms',
    'hours',
    'vehicle_sale_date',
    'tm_invoice_date',
    'warranty',
    'amc',
    'final_labour_amount',
    'final_spares_amount',
    'total_order_value',
    'delay_reason',
    'jobs_entry_complete',
    'supervisor',
    'invoiced',
    'invoice_format',
    'chassis_number',
    'branch',
  ],
  open_job_cards: [
    'job_card_number',
    'status',
    'vehicle_registration_number',
    'job_card_channel',
    'created_date_time',
    'completed_date_time',
    'closed_date_time',
    'service_request_no',
    'account',
    'last_name',
    'first_name',
    'labour_rate_list',
    'sr_assigned_to',
    'parts_price_list',
    'customer_po_ref',
    'delivery_variance_percent',
    'sr_type',
    'payment_type',
    'fms',
    'insurance_company_name',
    'insurance_type',
    'insurance_expiry_date',
    'open_for_days',
    'parts_entry_complete',
    'crn',
    'action_on_delay_reason',
    'arn',
    'account_phone_number',
    'contact_phones',
    'vehicle_delivery_date',
    'effective_final_delivery_estimate_date',
    'delivery_variance_hours',
    'effective_total_estimate',
    'total_estimate_variance_percent',
    'balance_payment_to_be_adjusted',
    'total_payment_amount_adjusted',
    'parent_product_line',
    'product_line',
    'division',
    'total_invoice_amount',
    'kms',
    'hours',
    'vehicle_sale_date',
    'tm_invoice_date',
    'warranty',
    'amc',
    'final_labour_amount',
    'final_spares_amount',
    'total_order_value',
    'delay_reason',
    'jobs_entry_complete',
    'supervisor',
    'invoiced',
    'invoice_format',
    'chassis_number',
    'branch',
  ],
  service_vas_jc_data: [
    // System columns
    'id',
    'branch',
    'created_at',
    'updated_at',
    // Text columns
    'job_card_number',
    'vrn',
    'complaint_code',
    'job_code',
    'job_description',
    'job_status',
    'chassis_number',
    'model',
    'product_line',
    'billing_type',
    'sr_assigned_to',
    'rate_type',
    'sr_type',
    'performed_by',
    'sr_number',
    // Numeric columns
    'net_price',
    'job_value',
    'discount',
    'billing_hours',
    // Timestamp column
    'jc_closed_date_time',
  ],
  service_parts_consumption_data: [
    'part_number',
    'part_description',
    'transaction_date',
    'otc_quantity',
    'ws_quantity',
    'quantity_consumed',
    'unit_cost',
    'total_cost',
    'source_reference',
    'source_row_hash',
    'branch',
  ],
  service_parts_order_data: [
    'part_number',
    'part_description',
    'order_date',
    'expected_date',
    'ordered_quantity',
    'received_quantity',
    'backorder_quantity',
    'status',
    'source_document_id',
    'source_row_hash',
    'branch',
  ],
  service_parts_stock_snapshot_data: [
    'part_number',
    'part_description',
    'snapshot_date',
    'on_hand_quantity',
    'weighted_cost',
    'inventory_value',
    'source_row_hash',
    'branch',
  ],
}

const DEFAULT_FALLBACK = ['part_number', 'part_description', 'branch']

export async function getTableColumns(tableName: string): Promise<string[]> {
  const { data, error } = await supabase.from(tableName).select('*').limit(1)

  if (!error && data && data.length > 0) {
    return Object.keys(data[0])
  }

  return FALLBACK_COLUMNS[tableName] ?? DEFAULT_FALLBACK
}
