project_id = "jmdndcphkmaljhwgzqxq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 5000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[functions.technician-daily-earnings-report]
verify_jwt = false

[functions.sa-earnings-report]
verify_jwt = false

[functions.bodyshop-earnings-report]
verify_jwt = false

[functions.booking-source-sync]
verify_jwt = false
