-- ============================================================
-- SUPABASE-002: Bodyshop Authoritative Alignment
-- Created: 2026-06-11
-- Source of truth: local_folder/backups/full_database.sql
-- Mirror source (size fallback): local_folder/backups/chunks/full_database.sql.part_*
-- ============================================================

-- 1) Core helper used by bodyshop_assignments trigger
CREATE OR REPLACE FUNCTION public.update_bodyshop_assignments_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- 2) Authoritative bodyshop_repair_cards table (2-table deployed model)
CREATE TABLE IF NOT EXISTS public.bodyshop_repair_cards (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_card_no text NOT NULL,
  reg_number text,
  customer_name text,
  customer_phone text,
  customer_type text,
  branch text,
  sa_employee_code text,
  sa_name text,
  current_stage integer NOT NULL DEFAULT 1,
  current_stage_name text NOT NULL DEFAULT 'vehicle_receiving',
  overall_status text NOT NULL DEFAULT 'active',
  doc_claim_form boolean DEFAULT false,
  doc_rc boolean DEFAULT false,
  doc_insurance boolean DEFAULT false,
  doc_dl boolean DEFAULT false,
  doc_aadhaar boolean DEFAULT false,
  doc_pan boolean DEFAULT false,
  doc_kyc boolean DEFAULT false,
  doc_gst boolean DEFAULT false,
  doc_company_pan boolean DEFAULT false,
  doc_bank_detail boolean DEFAULT false,
  survey_status text DEFAULT 'pending',
  survey_hold_reason text,
  claim_intimation_no text,
  surveyor_name text,
  surveyor_contact text,
  approved_parts text,
  customer_approved boolean DEFAULT false,
  estimation_by text,
  estimation_at timestamptz,
  estimation_approved_by text,
  denter_name text,
  denter_code text,
  painter_name text,
  painter_code text,
  technician_name text,
  technician_code text,
  floor_status text DEFAULT 'work_inprocess',
  floor_hold_reason text,
  additional_approval text,
  qc_status text DEFAULT 'pending',
  qc_checked_by text,
  qc_checked_at timestamptz,
  qc_fail_reason text,
  reinspection_type text,
  reinspection_by text,
  reinspection_at timestamptz,
  parts_entry_status text DEFAULT 'pending',
  billed_amount numeric(12,2),
  do_status text DEFAULT 'pending',
  do_amount numeric(12,2),
  customer_diff_amount numeric(12,2),
  payment_slip_url text,
  payment_status text DEFAULT 'pending',
  delivery_status text DEFAULT 'pending',
  delivery_marked_by text,
  delivery_marked_at timestamptz,
  received_at timestamptz DEFAULT now(),
  delivered_at timestamptz,
  created_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  insurance_policy_no text,
  insurance_company text,
  insurance_valid_date date,
  CONSTRAINT bodyshop_repair_cards_customer_type_check CHECK (customer_type = ANY (ARRAY['individual','firm','foc','cash'])),
  CONSTRAINT bodyshop_repair_cards_delivery_status_check CHECK (delivery_status = ANY (ARRAY['pending','done'])),
  CONSTRAINT bodyshop_repair_cards_do_status_check CHECK (do_status = ANY (ARRAY['pending','received','not_received'])),
  CONSTRAINT bodyshop_repair_cards_floor_status_check CHECK (floor_status = ANY (ARRAY['work_inprocess','hold','completed'])),
  CONSTRAINT bodyshop_repair_cards_overall_status_check CHECK (overall_status = ANY (ARRAY['active','delivered','cancelled'])),
  CONSTRAINT bodyshop_repair_cards_parts_entry_status_check CHECK (parts_entry_status = ANY (ARRAY['pending','entered','billed'])),
  CONSTRAINT bodyshop_repair_cards_payment_status_check CHECK (payment_status = ANY (ARRAY['pending','received','not_received'])),
  CONSTRAINT bodyshop_repair_cards_qc_status_check CHECK (qc_status = ANY (ARRAY['pending','pass','fail'])),
  CONSTRAINT bodyshop_repair_cards_reinspection_type_check CHECK (reinspection_type = ANY (ARRAY['team_member','surveyor'])),
  CONSTRAINT bodyshop_repair_cards_survey_status_check CHECK (survey_status = ANY (ARRAY['pending','hold','approved']))
);

-- 3) Authoritative bodyshop_assignments table
CREATE TABLE IF NOT EXISTS public.bodyshop_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_card_number text NOT NULL,
  role text NOT NULL,
  employee_code text NOT NULL,
  employee_name text NOT NULL,
  work_status text NOT NULL DEFAULT 'work_inprocess',
  remark text,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  assigned_by text,
  out_ts timestamptz,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bodyshop_assignments_role_check CHECK (role = ANY (ARRAY['DENTOR','PAINTER','TECHNICIAN'])),
  CONSTRAINT bodyshop_assignments_work_status_check CHECK (work_status = ANY (ARRAY['work_inprocess','hold','completed']))
);

-- 4) Authoritative bodyshop indexes
CREATE INDEX IF NOT EXISTS idx_brc_job_card ON public.bodyshop_repair_cards(job_card_no);
CREATE INDEX IF NOT EXISTS idx_brc_branch ON public.bodyshop_repair_cards(branch);
CREATE INDEX IF NOT EXISTS idx_brc_status ON public.bodyshop_repair_cards(overall_status);
CREATE INDEX IF NOT EXISTS idx_brc_stage ON public.bodyshop_repair_cards(current_stage);

CREATE INDEX IF NOT EXISTS idx_bodyshop_assignments_jc ON public.bodyshop_assignments(job_card_number);
CREATE INDEX IF NOT EXISTS idx_bodyshop_assignments_active ON public.bodyshop_assignments(is_active, assigned_at DESC);

-- 5) Trigger alignment
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'trg_bodyshop_assignments_updated_at'
      AND tgrelid = 'public.bodyshop_assignments'::regclass
  ) THEN
    CREATE TRIGGER trg_bodyshop_assignments_updated_at
    BEFORE UPDATE ON public.bodyshop_assignments
    FOR EACH ROW
    EXECUTE FUNCTION public.update_bodyshop_assignments_updated_at();
  END IF;
END
$$;

-- 6) Canonical module contract alignment (modules.name/label + user_module_permissions.module_id)
INSERT INTO public.modules (name, label, description, route, is_active)
VALUES (
  'bodyshop_repair',
  'Bodyshop Repair',
  'Track accidental vehicles through the full repair lifecycle',
  '/bodyshop-repair',
  true
)
ON CONFLICT (name)
DO UPDATE
SET
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  route = COALESCE(public.modules.route, EXCLUDED.route),
  is_active = true;

WITH target_module AS (
  SELECT id AS module_id
  FROM public.modules
  WHERE name = 'bodyshop_repair'
), missing_rows AS (
  SELECT
    u.id AS user_id,
    tm.module_id
  FROM public.users u
  CROSS JOIN target_module tm
  LEFT JOIN public.user_module_permissions ump
    ON ump.user_id = u.id
   AND ump.module_id = tm.module_id
  WHERE u.is_active = true
    AND ump.id IS NULL
)
INSERT INTO public.user_module_permissions (user_id, module_id, can_view, can_modify, can_delete, granted_by, granted_at)
SELECT user_id, module_id, true, false, false, NULL::uuid, now()
FROM missing_rows
ON CONFLICT (user_id, module_id) DO NOTHING;

-- 7) RLS + policies mirrored from authoritative deployed state
ALTER TABLE public.bodyshop_repair_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bodyshop_assignments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'bodyshop_repair_cards'
      AND policyname = 'admin_unrestricted_all_ops_v1'
  ) THEN
    CREATE POLICY admin_unrestricted_all_ops_v1
      ON public.bodyshop_repair_cards
      TO authenticated
      USING (public.is_admin())
      WITH CHECK (public.is_admin());
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'bodyshop_assignments'
      AND policyname = 'admin_unrestricted_all_ops_v1'
  ) THEN
    CREATE POLICY admin_unrestricted_all_ops_v1
      ON public.bodyshop_assignments
      TO authenticated
      USING (public.is_admin())
      WITH CHECK (public.is_admin());
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'bodyshop_assignments'
      AND policyname = 'bodyshop_assignments_read'
  ) THEN
    CREATE POLICY bodyshop_assignments_read
      ON public.bodyshop_assignments
      FOR SELECT
      TO authenticated
      USING (true);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'bodyshop_assignments'
      AND policyname = 'bodyshop_assignments_insert'
  ) THEN
    CREATE POLICY bodyshop_assignments_insert
      ON public.bodyshop_assignments
      FOR INSERT
      TO authenticated
      WITH CHECK (true);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'bodyshop_assignments'
      AND policyname = 'bodyshop_assignments_update'
  ) THEN
    CREATE POLICY bodyshop_assignments_update
      ON public.bodyshop_assignments
      FOR UPDATE
      TO authenticated
      USING (true);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'bodyshop_assignments'
      AND policyname = 'bodyshop_assignments_service_all'
  ) THEN
    CREATE POLICY bodyshop_assignments_service_all
      ON public.bodyshop_assignments
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END
$$;

-- 8) ACL surface mirrored from authoritative deployed state
GRANT ALL ON TABLE public.bodyshop_repair_cards TO anon;
GRANT ALL ON TABLE public.bodyshop_repair_cards TO authenticated;
GRANT ALL ON TABLE public.bodyshop_repair_cards TO service_role;

GRANT ALL ON TABLE public.bodyshop_assignments TO anon;
GRANT ALL ON TABLE public.bodyshop_assignments TO authenticated;
GRANT ALL ON TABLE public.bodyshop_assignments TO service_role;

GRANT ALL ON SEQUENCE public.bodyshop_repair_cards_id_seq TO anon;
GRANT ALL ON SEQUENCE public.bodyshop_repair_cards_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.bodyshop_repair_cards_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.bodyshop_assignments_id_seq TO anon;
GRANT ALL ON SEQUENCE public.bodyshop_assignments_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.bodyshop_assignments_id_seq TO service_role;

GRANT ALL ON FUNCTION public.update_bodyshop_assignments_updated_at() TO anon;
GRANT ALL ON FUNCTION public.update_bodyshop_assignments_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.update_bodyshop_assignments_updated_at() TO service_role;
