-- Plan: SUPABASE-002 Phase 5 (Fuel Granularity)
-- Purpose: Add granular powertrain_type (PETROL/DIESEL/CNG/EV) with deterministic derivation from product_line.

BEGIN;

ALTER TABLE public.all_service_data
  ADD COLUMN IF NOT EXISTS powertrain_type text;

COMMENT ON COLUMN public.all_service_data.powertrain_type
IS 'Granular derived powertrain classification from product_line. Values: EV, CNG, DIESEL, PETROL, UNKNOWN (audit fallback), NULL when product_line is blank.';

CREATE TABLE IF NOT EXISTS public.all_service_data_powertrain_overrides (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_pattern text NOT NULL,
  powertrain_type text NOT NULL CHECK (powertrain_type IN ('EV', 'CNG', 'DIESEL', 'PETROL', 'UNKNOWN')),
  priority integer NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS all_service_data_powertrain_overrides_active_priority_idx
  ON public.all_service_data_powertrain_overrides (is_active, priority, id);

COMMENT ON TABLE public.all_service_data_powertrain_overrides
IS 'Manual override rules for product_line to powertrain_type mapping. Used after explicit token rules; enables one-by-one UNKNOWN resolution.';

CREATE OR REPLACE FUNCTION public.calc_all_service_powertrain_type(
  p_product_line text
)
RETURNS text
LANGUAGE sql
STABLE
AS $$
  WITH normalized AS (
    SELECT upper(btrim(COALESCE(p_product_line, ''))) AS pl
  ), base AS (
    SELECT
      CASE
        WHEN n.pl = '' THEN NULL
        WHEN n.pl LIKE '%EV%' THEN 'EV'
        WHEN n.pl LIKE '%CNG%' THEN 'CNG'
        WHEN (
          n.pl ~ '(^|[^A-Z0-9])QJET([^A-Z0-9]|$)'
          OR n.pl LIKE '%DICOR%'
          OR n.pl ~ '(^|[^A-Z0-9])CR4([^A-Z0-9]|$)'
          OR n.pl LIKE '%(D)%'
          OR n.pl LIKE '%DIESEL%'
          OR n.pl LIKE '%1.05 D%'
          OR n.pl ~ '(^|[^0-9])1\.5([^0-9]|$)'
        ) THEN 'DIESEL'
        WHEN (
          n.pl LIKE '%(P)%'
          OR n.pl LIKE '%PETROL%'
          OR n.pl LIKE '%1.2 P%'
          OR n.pl LIKE '%1.0 P%'
          OR n.pl LIKE '%GDI%'
        ) THEN 'PETROL'
        ELSE NULL
      END AS base_result,
      n.pl
    FROM normalized n
  ), ov AS (
    SELECT o.powertrain_type
    FROM base b
    JOIN public.all_service_data_powertrain_overrides o
      ON o.is_active = true
     AND b.pl LIKE upper(o.match_pattern)
    ORDER BY o.priority ASC, o.id ASC
    LIMIT 1
  )
  SELECT
    CASE
      WHEN b.base_result IS NOT NULL THEN b.base_result
      WHEN EXISTS (SELECT 1 FROM ov) THEN (SELECT powertrain_type FROM ov)
      WHEN b.pl = '' THEN NULL
      ELSE 'UNKNOWN'
    END
  FROM base b;
$$;

COMMENT ON FUNCTION public.calc_all_service_powertrain_type(text)
IS 'Deterministic powertrain mapping from product_line. Ordered rules: EV/CNG/DIESEL/PETROL explicit markers, then active override table match_pattern by priority, else UNKNOWN; blank => NULL.';

CREATE OR REPLACE FUNCTION public.set_all_service_powertrain_type()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.powertrain_type := public.calc_all_service_powertrain_type(NEW.product_line);
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.set_all_service_powertrain_type()
IS 'Maintains all_service_data.powertrain_type on INSERT and product_line updates.';

DROP TRIGGER IF EXISTS trg_set_all_service_powertrain_type
  ON public.all_service_data;

CREATE TRIGGER trg_set_all_service_powertrain_type
BEFORE INSERT OR UPDATE OF product_line
ON public.all_service_data
FOR EACH ROW
EXECUTE FUNCTION public.set_all_service_powertrain_type();

-- Backfill existing rows deterministically.
UPDATE public.all_service_data a
SET powertrain_type = public.calc_all_service_powertrain_type(a.product_line)
WHERE a.powertrain_type IS DISTINCT FROM public.calc_all_service_powertrain_type(a.product_line);

COMMIT;
