-- Generated seed fragment. Do not apply alone.
(1, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Distilled Water', 20, 0, true),
(2, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Shampoo', 120, 0, true),
(3, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Seat Protection Cover', 80, 0, true),
(4, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Coolant Top Up', 100, 0, true),
(5, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Oil Filter Change', 179, 0, true),
(6, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Sunroof Greece', 800, 0, true),
(7, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'AC Disinfection', 800, 0, true),
(8, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Antirust Underbody', 1900, 0, true),
(9, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Antirust Cavity', 1600, 0, true),
(10, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Interior cleaning', 1300, 0, true),
(11, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Interior cleaning standard', 875, 0, true),
(12, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Paint Protection', 1100, 0, true),
(13, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Service Pro Plus', 300, 0, true),
(14, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Surface Coating', 1800, 0, true),
(15, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Engine Wiring Surface', 800, 0, true),
(16, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Oil Flushing', 800, 0, true),
(17, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'TBC Clean', 800, 0, true),
(18, 'GLOBAL', 'First Free Service', 'Altroz', 'Petrol', 'Exhaust Cleaning', 1200, 0, true),
(19, 'GLOBAL', 'First Free Service', 'Altroz', 'Diesel', 'Distilled Water', 20, 0, true),
(20, 'GLOBAL', 'First Free Service', 'Altroz', 'Diesel', 'Shampoo', 120, 0, true),
(21, 'GLOBAL', 'First Free Service', 'Altroz', 'Diesel', 'Coolant Top Up', 100, 0, true),
(22, 'GLOBAL', 'First Free Service', 'Altroz', 'Diesel', 'Oil Filter Change', 192, 0, true),
(23, 'GLOBAL', 'First Free Service', 'Altroz', 'Diesel', 'Sunroof Greece', 800, 0, true),
(24, 'GLOBAL', 'First Free Service', 'Altroz', 'CNG', 'Distilled Water', 20, 0, true),
(25, 'GLOBAL', 'First Free Service', 'Altroz', 'CNG', 'Shampoo', 120, 0, true),
(26, 'GLOBAL', 'First Free Service', 'Altroz', 'CNG', 'Coolant Top Up', 100, 0, true),
(27, 'GLOBAL', 'First Free Service', 'Altroz', 'CNG', 'Oil Filter Change', 179, 0, true),
(28, 'GLOBAL', 'First Free Service', 'Altroz', 'CNG', 'Sunroof Greece', 800, 0, true),
(29, 'GLOBAL', 'First Free Service', 'Tiago', 'Petrol', 'Distilled Water', 20, 0, true),
(30, 'GLOBAL', 'First Free Service', 'Tiago', 'Petrol', 'Shampoo', 120, 0, true),
(31, 'GLOBAL', 'First Free Service', 'Tiago', 'Petrol', 'Coolant Top Up', 100, 0, true),
(32, 'GLOBAL', 'First Free Service', 'Tiago', 'Petrol', 'Oil Filter Change', 179, 0, true),
(33, 'GLOBAL', 'First Free Service', 'Tiago', 'Diesel', 'Distilled Water', 20, 0, true),
(34, 'GLOBAL', 'First Free Service', 'Tiago', 'Diesel', 'Shampoo', 120, 0, true),
(35, 'GLOBAL', 'First Free Service', 'Tiago', 'Diesel', 'Coolant Top Up', 100, 0, true),
(36, 'GLOBAL', 'First Free Service', 'Tiago', 'Diesel', 'Oil Filter Change', 192, 0, true),
(37, 'GLOBAL', 'First Free Service', 'Tiago', 'CNG', 'Distilled Water', 20, 0, true),
(38, 'GLOBAL', 'First Free Service', 'Tiago', 'CNG', 'Shampoo', 120, 0, true),
(39, 'GLOBAL', 'First Free Service', 'Tiago', 'CNG', 'Coolant Top Up', 100, 0, true),
(40, 'GLOBAL', 'First Free Service', 'Tiago', 'CNG', 'Oil Filter Change', 170, 0, true),
(41, 'GLOBAL', 'First Free Service', 'Tiago', 'EV', 'Distilled Water', 20, 0, true),
(42, 'GLOBAL', 'First Free Service', 'Tiago', 'EV', 'Shampoo', 120, 0, true),
(43, 'GLOBAL', 'First Free Service', 'Tiago', 'EV', 'Coolant Top Up', 212, 0, true),
(44, 'GLOBAL', 'First Free Service', 'Nexon', 'Petrol', 'Distilled Water', 20, 0, true),
(45, 'GLOBAL', 'First Free Service', 'Nexon', 'Petrol', 'Shampoo', 120, 0, true),
(46, 'GLOBAL', 'First Free Service', 'Nexon', 'Petrol', 'Coolant Top Up', 100, 0, true),
(47, 'GLOBAL', 'First Free Service', 'Nexon', 'Petrol', 'Oil Filter Change', 179, 0, true),
(48, 'GLOBAL', 'First Free Service', 'Nexon', 'Petrol', 'Sunroof Greece', 800, 0, true),
(49, 'GLOBAL', 'First Free Service', 'Nexon', 'Diesel', 'Distilled Water', 20, 0, true),
(50, 'GLOBAL', 'First Free Service', 'Nexon', 'Diesel', 'Shampoo', 120, 0, true),
(51, 'GLOBAL', 'First Free Service', 'Nexon', 'Diesel', 'Coolant Top Up', 100, 0, true),
(52, 'GLOBAL', 'First Free Service', 'Nexon', 'Diesel', 'Oil Filter Change', 192, 0, true),
(53, 'GLOBAL', 'First Free Service', 'Nexon', 'Diesel', 'Sunroof Greece', 800, 0, true),
(54, 'GLOBAL', 'First Free Service', 'Nexon', 'CNG', 'Distilled Water', 20, 0, true),
(55, 'GLOBAL', 'First Free Service', 'Nexon', 'CNG', 'Shampoo', 120, 0, true),
(56, 'GLOBAL', 'First Free Service', 'Nexon', 'CNG', 'Coolant Top Up', 100, 0, true),
(57, 'GLOBAL', 'First Free Service', 'Nexon', 'CNG', 'Oil Filter Change', 192, 0, true),
(58, 'GLOBAL', 'First Free Service', 'Nexon', 'CNG', 'Sunroof Greece', 800, 0, true),
(59, 'GLOBAL', 'First Free Service', 'Nexon', 'EV', 'Distilled Water', 20, 0, true),
(60, 'GLOBAL', 'First Free Service', 'Nexon', 'EV', 'Shampoo', 120, 0, true),
(61, 'GLOBAL', 'First Free Service', 'Nexon', 'EV', 'Coolant Top Up', 212, 0, true),
(62, 'GLOBAL', 'First Free Service', 'Nexon', 'EV', 'Sunroof Greece', 800, 0, true),
(63, 'GLOBAL', 'First Free Service', 'Punch', 'Petrol', 'Distilled Water', 20, 0, true),
(64, 'GLOBAL', 'First Free Service', 'Punch', 'Petrol', 'Shampoo', 120, 0, true),
(65, 'GLOBAL', 'First Free Service', 'Punch', 'Petrol', 'Coolant Top Up', 100, 0, true),
(66, 'GLOBAL', 'First Free Service', 'Punch', 'Petrol', 'Oil Filter Change', 179, 0, true),
(67, 'GLOBAL', 'First Free Service', 'Punch', 'Petrol', 'Sunroof Greece', 800, 0, true),
(68, 'GLOBAL', 'First Free Service', 'Punch', 'CNG', 'Distilled Water', 20, 0, true),
(69, 'GLOBAL', 'First Free Service', 'Punch', 'CNG', 'Shampoo', 120, 0, true),
(70, 'GLOBAL', 'First Free Service', 'Punch', 'CNG', 'Coolant Top Up', 100, 0, true),
(71, 'GLOBAL', 'First Free Service', 'Punch', 'CNG', 'Oil Filter Change', 179, 0, true),
(72, 'GLOBAL', 'First Free Service', 'Punch', 'CNG', 'Sunroof Greece', 800, 0, true),
(73, 'GLOBAL', 'First Free Service', 'Punch', 'EV', 'Distilled Water', 20, 0, true),
(74, 'GLOBAL', 'First Free Service', 'Punch', 'EV', 'Shampoo', 120, 0, true),
(75, 'GLOBAL', 'First Free Service', 'Punch', 'EV', 'Coolant Top Up', 212, 0, true),
(76, 'GLOBAL', 'First Free Service', 'Punch', 'EV', 'Sunroof Greece', 800, 0, true),
(77, 'GLOBAL', 'First Free Service', 'Tigor', 'Petrol', 'Distilled Water', 20, 0, true),
(78, 'GLOBAL', 'First Free Service', 'Tigor', 'Petrol', 'Shampoo', 120, 0, true),
(79, 'GLOBAL', 'First Free Service', 'Tigor', 'Petrol', 'Coolant Top Up', 100, 0, true),
(80, 'GLOBAL', 'First Free Service', 'Tigor', 'Petrol', 'Oil Filter Change', 179, 0, true),
(81, 'GLOBAL', 'First Free Service', 'Tigor', 'Diesel', 'Distilled Water', 20, 0, true),
(82, 'GLOBAL', 'First Free Service', 'Tigor', 'Diesel', 'Shampoo', 120, 0, true),
(83, 'GLOBAL', 'First Free Service', 'Tigor', 'Diesel', 'Coolant Top Up', 100, 0, true),
(84, 'GLOBAL', 'First Free Service', 'Tigor', 'Diesel', 'Oil Filter Change', 192, 0, true),
(85, 'GLOBAL', 'First Free Service', 'Tigor', 'CNG', 'Distilled Water', 20, 0, true),
(86, 'GLOBAL', 'First Free Service', 'Tigor', 'CNG', 'Shampoo', 120, 0, true),
(87, 'GLOBAL', 'First Free Service', 'Tigor', 'CNG', 'Coolant Top Up', 100, 0, true),
(88, 'GLOBAL', 'First Free Service', 'Tigor', 'CNG', 'Oil Filter Change', 170, 0, true),
(89, 'GLOBAL', 'First Free Service', 'Tigor', 'EV', 'Distilled Water', 20, 0, true),
(90, 'GLOBAL', 'First Free Service', 'Tigor', 'EV', 'Shampoo', 120, 0, true),
(91, 'GLOBAL', 'First Free Service', 'Tigor', 'EV', 'Coolant Top Up', 212, 0, true),
(92, 'GLOBAL', 'First Free Service', 'Curvv', 'Petrol', 'Shampoo', 120, 0, true),
(93, 'GLOBAL', 'First Free Service', 'Curvv', 'Petrol', 'Coolant Top Up', 100, 0, true),
(94, 'GLOBAL', 'First Free Service', 'Curvv', 'Petrol', 'Oil Filter Change', 0, 0, true),
(95, 'GLOBAL', 'First Free Service', 'Curvv', 'Petrol', 'Sunroof Greece', 800, 0, true),
(96, 'GLOBAL', 'First Free Service', 'Curvv', 'Diesel', 'Distilled Water', 20, 0, true),
(97, 'GLOBAL', 'First Free Service', 'Curvv', 'Diesel', 'Shampoo', 120, 0, true),
(98, 'GLOBAL', 'First Free Service', 'Curvv', 'Diesel', 'Coolant Top Up', 100, 0, true),
(99, 'GLOBAL', 'First Free Service', 'Curvv', 'Diesel', 'Oil Filter Change', 0, 0, true),
(100, 'GLOBAL', 'First Free Service', 'Curvv', 'Diesel', 'Sunroof Greece', 800, 0, true),
(101, 'GLOBAL', 'First Free Service', 'Curvv', 'EV', 'Distilled Water', 20, 0, true),
(102, 'GLOBAL', 'First Free Service', 'Curvv', 'EV', 'Shampoo', 120, 0, true),
(103, 'GLOBAL', 'First Free Service', 'Curvv', 'EV', 'Coolant Top Up', 212, 0, true),
(104, 'GLOBAL', 'First Free Service', 'Curvv', 'EV', 'Sunroof Greece', 800, 0, true),
(105, 'GLOBAL', 'First Free Service', 'Harrier', 'Diesel', 'Distilled Water', 20, 0, true),
(106, 'GLOBAL', 'First Free Service', 'Harrier', 'Diesel', 'Shampoo', 120, 0, true),
(107, 'GLOBAL', 'First Free Service', 'Harrier', 'Diesel', 'Coolant Top Up', 100, 0, true),
(108, 'GLOBAL', 'First Free Service', 'Harrier', 'Diesel', 'Oil Filter Change', 850, 0, true),
(109, 'GLOBAL', 'First Free Service', 'Harrier', 'Diesel', 'Sunroof Greece', 800, 0, true),
(110, 'GLOBAL', 'First Free Service', 'Harrier', 'Diesel', 'Def', 620, 0, true),
(111, 'GLOBAL', 'First Free Service', 'Safari', 'Diesel', 'Distilled Water', 20, 0, true),
(112, 'GLOBAL', 'First Free Service', 'Safari', 'Diesel', 'Shampoo', 120, 0, true),
(113, 'GLOBAL', 'First Free Service', 'Safari', 'Diesel', 'Coolant Top Up', 100, 0, true),
(114, 'GLOBAL', 'First Free Service', 'Safari', 'Diesel', 'Oil Filter Change', 850, 0, true),
(115, 'GLOBAL', 'First Free Service', 'Safari', 'Diesel', 'Sunroof Greece', 800, 0, true),
(116, 'GLOBAL', 'First Free Service', 'Safari', 'Diesel', 'Def', 620, 0, true),
(117, 'GLOBAL', 'Second Free Service', 'Altroz', 'Petrol', 'Distilled Water', 20, 0, true),
(118, 'GLOBAL', 'Second Free Service', 'Altroz', 'Petrol', 'Shampoo', 120, 0, true),
(119, 'GLOBAL', 'Second Free Service', 'Altroz', 'Petrol', 'Coolant Top Up', 100, 0, true),
(120, 'GLOBAL', 'Second Free Service', 'Altroz', 'Petrol', 'Oil Filter Change', 179, 0, true),
(121, 'GLOBAL', 'Second Free Service', 'Altroz', 'Petrol', 'Sunroof Greece', 800, 0, true),
(122, 'GLOBAL', 'Second Free Service', 'Altroz', 'Diesel', 'Distilled Water', 20, 0, true),
(123, 'GLOBAL', 'Second Free Service', 'Altroz', 'Diesel', 'Shampoo', 120, 0, true),
(124, 'GLOBAL', 'Second Free Service', 'Altroz', 'Diesel', 'Coolant Top Up', 100, 0, true),
(125, 'GLOBAL', 'Second Free Service', 'Altroz', 'Diesel', 'Oil Filter Change', 192, 0, true),
(126, 'GLOBAL', 'Second Free Service', 'Altroz', 'Diesel', 'Sunroof Greece', 800, 0, true),
(127, 'GLOBAL', 'Second Free Service', 'Altroz', 'CNG', 'Distilled Water', 20, 0, true),
(128, 'GLOBAL', 'Second Free Service', 'Altroz', 'CNG', 'Shampoo', 120, 0, true),
(129, 'GLOBAL', 'Second Free Service', 'Altroz', 'CNG', 'Coolant Top Up', 100, 0, true),
(130, 'GLOBAL', 'Second Free Service', 'Altroz', 'CNG', 'Oil Filter Change', 179, 0, true),
(131, 'GLOBAL', 'Second Free Service', 'Altroz', 'CNG', 'Sunroof Greece', 800, 0, true),
(132, 'GLOBAL', 'Second Free Service', 'Tiago', 'Petrol', 'Distilled Water', 20, 0, true),
(133, 'GLOBAL', 'Second Free Service', 'Tiago', 'Petrol', 'Shampoo', 120, 0, true),
(134, 'GLOBAL', 'Second Free Service', 'Tiago', 'Petrol', 'Coolant Top Up', 100, 0, true),
(135, 'GLOBAL', 'Second Free Service', 'Tiago', 'Petrol', 'Oil Filter Change', 179, 0, true),
(136, 'GLOBAL', 'Second Free Service', 'Tiago', 'Diesel', 'Distilled Water', 20, 0, true),
(137, 'GLOBAL', 'Second Free Service', 'Tiago', 'Diesel', 'Shampoo', 120, 0, true),
(138, 'GLOBAL', 'Second Free Service', 'Tiago', 'Diesel', 'Coolant Top Up', 100, 0, true),
(139, 'GLOBAL', 'Second Free Service', 'Tiago', 'Diesel', 'Oil Filter Change', 192, 0, true),
(140, 'GLOBAL', 'Second Free Service', 'Tiago', 'CNG', 'Distilled Water', 20, 0, true),
(141, 'GLOBAL', 'Second Free Service', 'Tiago', 'CNG', 'Shampoo', 120, 0, true),
(142, 'GLOBAL', 'Second Free Service', 'Tiago', 'CNG', 'Coolant Top Up', 100, 0, true),
(143, 'GLOBAL', 'Second Free Service', 'Tiago', 'CNG', 'Oil Filter Change', 179, 0, true),
(144, 'GLOBAL', 'Second Free Service', 'Tiago', 'EV', 'Distilled Water', 20, 0, true),
(145, 'GLOBAL', 'Second Free Service', 'Tiago', 'EV', 'Shampoo', 120, 0, true),
(146, 'GLOBAL', 'Second Free Service', 'Tiago', 'EV', 'Coolant Top Up', 212, 0, true),
(147, 'GLOBAL', 'Second Free Service', 'Nexon', 'Petrol', 'Distilled Water', 20, 0, true),
(148, 'GLOBAL', 'Second Free Service', 'Nexon', 'Petrol', 'Shampoo', 120, 0, true),
(149, 'GLOBAL', 'Second Free Service', 'Nexon', 'Petrol', 'Coolant Top Up', 100, 0, true),
(150, 'GLOBAL', 'Second Free Service', 'Nexon', 'Petrol', 'Oil Filter Change', 179, 0, true),
(151, 'GLOBAL', 'Second Free Service', 'Nexon', 'Petrol', 'Sunroof Greece', 800, 0, true),
(152, 'GLOBAL', 'Second Free Service', 'Nexon', 'Diesel', 'Distilled Water', 20, 0, true),
(153, 'GLOBAL', 'Second Free Service', 'Nexon', 'Diesel', 'Shampoo', 120, 0, true),
(154, 'GLOBAL', 'Second Free Service', 'Nexon', 'Diesel', 'Coolant Top Up', 100, 0, true),
(155, 'GLOBAL', 'Second Free Service', 'Nexon', 'Diesel', 'Oil Filter Change', 192, 0, true),
(156, 'GLOBAL', 'Second Free Service', 'Nexon', 'Diesel', 'Sunroof Greece', 800, 0, true),
(157, 'GLOBAL', 'Second Free Service', 'Nexon', 'CNG', 'Distilled Water', 20, 0, true),
(158, 'GLOBAL', 'Second Free Service', 'Nexon', 'CNG', 'Shampoo', 120, 0, true),
(159, 'GLOBAL', 'Second Free Service', 'Nexon', 'CNG', 'Coolant Top Up', 100, 0, true),
(160, 'GLOBAL', 'Second Free Service', 'Nexon', 'CNG', 'Oil Filter Change', 179, 0, true),
(161, 'GLOBAL', 'Second Free Service', 'Nexon', 'CNG', 'Sunroof Greece', 800, 0, true),
(162, 'GLOBAL', 'Second Free Service', 'Nexon', 'EV', 'Distilled Water', 20, 0, true),
(163, 'GLOBAL', 'Second Free Service', 'Nexon', 'EV', 'Shampoo', 120, 0, true),
(164, 'GLOBAL', 'Second Free Service', 'Nexon', 'EV', 'Coolant Top Up', 212, 0, true),
(165, 'GLOBAL', 'Second Free Service', 'Nexon', 'EV', 'Sunroof Greece', 800, 0, true),
(166, 'GLOBAL', 'Second Free Service', 'Punch', 'Petrol', 'Distilled Water', 20, 0, true),
(167, 'GLOBAL', 'Second Free Service', 'Punch', 'Petrol', 'Shampoo', 120, 0, true),
(168, 'GLOBAL', 'Second Free Service', 'Punch', 'Petrol', 'Coolant Top Up', 100, 0, true),
(169, 'GLOBAL', 'Second Free Service', 'Punch', 'Petrol', 'Oil Filter Change', 179, 0, true),
(170, 'GLOBAL', 'Second Free Service', 'Punch', 'Petrol', 'Sunroof Greece', 800, 0, true),
(171, 'GLOBAL', 'Second Free Service', 'Punch', 'Petrol', 'oil Top up', 273, 0, true),
(172, 'GLOBAL', 'Second Free Service', 'Punch', 'CNG', 'Distilled Water', 20, 0, true),
(173, 'GLOBAL', 'Second Free Service', 'Punch', 'CNG', 'Shampoo', 120, 0, true),
(174, 'GLOBAL', 'Second Free Service', 'Punch', 'CNG', 'Coolant Top Up', 100, 0, true),
(175, 'GLOBAL', 'Second Free Service', 'Punch', 'CNG', 'Oil Filter Change', 179, 0, true),
(176, 'GLOBAL', 'Second Free Service', 'Punch', 'CNG', 'Sunroof Greece', 800, 0, true),
(177, 'GLOBAL', 'Second Free Service', 'Punch', 'EV', 'Distilled Water', 20, 0, true),
(178, 'GLOBAL', 'Second Free Service', 'Punch', 'EV', 'Shampoo', 120, 0, true),
(179, 'GLOBAL', 'Second Free Service', 'Punch', 'EV', 'Coolant Top Up', 212, 0, true),
(180, 'GLOBAL', 'Second Free Service', 'Punch', 'EV', 'Sunroof Greece', 800, 0, true),
(181, 'GLOBAL', 'Second Free Service', 'Tigor', 'Petrol', 'Distilled Water', 20, 0, true),
(182, 'GLOBAL', 'Second Free Service', 'Tigor', 'Petrol', 'Shampoo', 120, 0, true),
(183, 'GLOBAL', 'Second Free Service', 'Tigor', 'Petrol', 'Coolant Top Up', 100, 0, true),
(184, 'GLOBAL', 'Second Free Service', 'Tigor', 'Petrol', 'Oil Filter Change', 179, 0, true),
(185, 'GLOBAL', 'Second Free Service', 'Tigor', 'Diesel', 'Distilled Water', 20, 0, true),
(186, 'GLOBAL', 'Second Free Service', 'Tigor', 'Diesel', 'Shampoo', 120, 0, true),
(187, 'GLOBAL', 'Second Free Service', 'Tigor', 'Diesel', 'Coolant Top Up', 100, 0, true),
(188, 'GLOBAL', 'Second Free Service', 'Tigor', 'Diesel', 'Oil Filter Change', 192, 0, true),
(189, 'GLOBAL', 'Second Free Service', 'Tigor', 'CNG', 'Distilled Water', 20, 0, true),
(190, 'GLOBAL', 'Second Free Service', 'Tigor', 'CNG', 'Shampoo', 120, 0, true),
(191, 'GLOBAL', 'Second Free Service', 'Tigor', 'CNG', 'Coolant Top Up', 100, 0, true),
(192, 'GLOBAL', 'Second Free Service', 'Tigor', 'CNG', 'Oil Filter Change', 179, 0, true),
(193, 'GLOBAL', 'Second Free Service', 'Tigor', 'EV', 'Distilled Water', 20, 0, true),
(194, 'GLOBAL', 'Second Free Service', 'Tigor', 'EV', 'Shampoo', 120, 0, true),
(195, 'GLOBAL', 'Second Free Service', 'Tigor', 'EV', 'Coolant Top Up', 212, 0, true),
(196, 'GLOBAL', 'Second Free Service', 'Curvv', 'Petrol', 'Shampoo', 120, 0, true),
(197, 'GLOBAL', 'Second Free Service', 'Curvv', 'Petrol', 'Coolant Top Up', 100, 0, true),
(198, 'GLOBAL', 'Second Free Service', 'Curvv', 'Petrol', 'Oil Filter Change', 0, 0, true),
(199, 'GLOBAL', 'Second Free Service', 'Curvv', 'Petrol', 'Sunroof Greece', 800, 0, true),
(200, 'GLOBAL', 'Second Free Service', 'Curvv', 'Diesel', 'Distilled Water', 20, 0, true),
(201, 'GLOBAL', 'Second Free Service', 'Curvv', 'Diesel', 'Shampoo', 120, 0, true),
(202, 'GLOBAL', 'Second Free Service', 'Curvv', 'Diesel', 'Coolant Top Up', 100, 0, true),
(203, 'GLOBAL', 'Second Free Service', 'Curvv', 'Diesel', 'Oil Filter Change', 0, 0, true),
(204, 'GLOBAL', 'Second Free Service', 'Curvv', 'Diesel', 'Sunroof Greece', 800, 0, true),
(205, 'GLOBAL', 'Second Free Service', 'Curvv', 'EV', 'Distilled Water', 20, 0, true),
(206, 'GLOBAL', 'Second Free Service', 'Curvv', 'EV', 'Shampoo', 120, 0, true),
(207, 'GLOBAL', 'Second Free Service', 'Curvv', 'EV', 'Coolant Top Up', 212, 0, true),
(208, 'GLOBAL', 'Second Free Service', 'Curvv', 'EV', 'Sunroof Greece', 800, 0, true),
(209, 'GLOBAL', 'Second Free Service', 'Harrier', 'Diesel', 'Distilled Water', 20, 0, true),
(210, 'GLOBAL', 'Second Free Service', 'Harrier', 'Diesel', 'Shampoo', 120, 0, true),
(211, 'GLOBAL', 'Second Free Service', 'Harrier', 'Diesel', 'Coolant Top Up', 100, 0, true),
(212, 'GLOBAL', 'Second Free Service', 'Harrier', 'Diesel', 'Oil Filter Change', 850, 0, true),
(213, 'GLOBAL', 'Second Free Service', 'Harrier', 'Diesel', 'Sunroof Greece', 800, 0, true),
(214, 'GLOBAL', 'Second Free Service', 'Harrier', 'Diesel', 'Def', 620, 0, true),
(215, 'GLOBAL', 'Second Free Service', 'Safari', 'Diesel', 'Distilled Water', 20, 0, true),
(216, 'GLOBAL', 'Second Free Service', 'Safari', 'Diesel', 'Shampoo', 120, 0, true),
(217, 'GLOBAL', 'Second Free Service', 'Safari', 'Diesel', 'Coolant Top Up', 100, 0, true),
(218, 'GLOBAL', 'Second Free Service', 'Safari', 'Diesel', 'Oil Filter Change', 792, 0, true),
(219, 'GLOBAL', 'Second Free Service', 'Safari', 'Diesel', 'Sunroof Greece', 800, 0, true),
(220, 'GLOBAL', 'Second Free Service', 'Safari', 'Diesel', 'oil Top up', 650, 0, true),
(221, 'GLOBAL', 'Second Free Service', 'Safari', 'Diesel', 'Def', 620, 0, true),
(222, 'GLOBAL', 'Third Free Service', 'Altroz', 'Petrol', 'Distilled Water', 20, 0, true),
(223, 'GLOBAL', 'Third Free Service', 'Altroz', 'Petrol', 'Shampoo', 120, 0, true),
(224, 'GLOBAL', 'Third Free Service', 'Altroz', 'Petrol', 'Coolant Top Up', 100, 0, true),
(225, 'GLOBAL', 'Third Free Service', 'Altroz', 'Petrol', 'Engine Oil', 2159.5, 0, true),
(226, 'GLOBAL', 'Third Free Service', 'Altroz', 'Petrol', 'Oil Filter Change', 179, 0, true),
(227, 'GLOBAL', 'Third Free Service', 'Altroz', 'Petrol', 'AC Filter', 347, 0, true),
(228, 'GLOBAL', 'Third Free Service', 'Altroz', 'Petrol', 'Sunroof Greece', 800, 0, true),
(229, 'GLOBAL', 'Third Free Service', 'Altroz', 'Petrol', 'Air Filter', 850, 0, true),
(230, 'GLOBAL', 'Third Free Service', 'Altroz', 'Petrol', 'Alignment', 737, 0, true),
(231, 'GLOBAL', 'Third Free Service', 'Altroz', 'Petrol', 'Balancing', 550, 0, true),
(232, 'GLOBAL', 'Third Free Service', 'Altroz', 'Diesel', 'Distilled Water', 20, 0, true),
(233, 'GLOBAL', 'Third Free Service', 'Altroz', 'Diesel', 'Shampoo', 120, 0, true),
(234, 'GLOBAL', 'Third Free Service', 'Altroz', 'Diesel', 'Coolant Top Up', 100, 0, true),
(235, 'GLOBAL', 'Third Free Service', 'Altroz', 'Diesel', 'Engine Oil', 3085, 0, true),
(236, 'GLOBAL', 'Third Free Service', 'Altroz', 'Diesel', 'Oil Filter Change', 192, 0, true),
(237, 'GLOBAL', 'Third Free Service', 'Altroz', 'Diesel', 'AC Filter', 347, 0, true),
(238, 'GLOBAL', 'Third Free Service', 'Altroz', 'Diesel', 'Sunroof Greece', 800, 0, true),
(239, 'GLOBAL', 'Third Free Service', 'Altroz', 'CNG', 'Distilled Water', 20, 0, true),
(240, 'GLOBAL', 'Third Free Service', 'Altroz', 'CNG', 'Shampoo', 120, 0, true),
(241, 'GLOBAL', 'Third Free Service', 'Altroz', 'CNG', 'Coolant Top Up', 100, 0, true),
(242, 'GLOBAL', 'Third Free Service', 'Altroz', 'CNG', 'Engine Oil', 2159.5, 0, true),
(243, 'GLOBAL', 'Third Free Service', 'Altroz', 'CNG', 'Oil Filter Change', 179, 0, true),
(244, 'GLOBAL', 'Third Free Service', 'Altroz', 'CNG', 'AC Filter', 347, 0, true),
(245, 'GLOBAL', 'Third Free Service', 'Altroz', 'CNG', 'Sunroof Greece', 800, 0, true),
(246, 'GLOBAL', 'Third Free Service', 'Altroz', 'CNG', 'Alignment', 750, 0, true),
(247, 'GLOBAL', 'Third Free Service', 'Altroz', 'CNG', 'Balancing', 550, 0, true),
(248, 'GLOBAL', 'Third Free Service', 'Altroz', 'CNG', 'Air Filter', 750, 0, true),
(249, 'GLOBAL', 'Third Free Service', 'Tiago', 'Petrol', 'Distilled Water', 20, 0, true),
(250, 'GLOBAL', 'Third Free Service', 'Tiago', 'Petrol', 'Shampoo', 120, 0, true),
(251, 'GLOBAL', 'Third Free Service', 'Tiago', 'Petrol', 'Coolant Top Up', 100, 0, true),
(252, 'GLOBAL', 'Third Free Service', 'Tiago', 'Petrol', 'Engine Oil', 2159.5, 0, true),
(253, 'GLOBAL', 'Third Free Service', 'Tiago', 'Petrol', 'Oil Filter Change', 179, 0, true),
(254, 'GLOBAL', 'Third Free Service', 'Tiago', 'Petrol', 'AC Filter', 241, 0, true),
(255, 'GLOBAL', 'Third Free Service', 'Tiago', 'Diesel', 'Distilled Water', 20, 0, true),
(256, 'GLOBAL', 'Third Free Service', 'Tiago', 'Diesel', 'Shampoo', 120, 0, true),
(257, 'GLOBAL', 'Third Free Service', 'Tiago', 'Diesel', 'Coolant Top Up', 100, 0, true),
(258, 'GLOBAL', 'Third Free Service', 'Tiago', 'Diesel', 'Engine Oil', 3085, 0, true),
(259, 'GLOBAL', 'Third Free Service', 'Tiago', 'Diesel', 'Oil Filter Change', 192, 0, true),
(260, 'GLOBAL', 'Third Free Service', 'Tiago', 'Diesel', 'AC Filter', 241, 0, true),
(261, 'GLOBAL', 'Third Free Service', 'Tiago', 'CNG', 'Distilled Water', 20, 0, true),
(262, 'GLOBAL', 'Third Free Service', 'Tiago', 'CNG', 'Shampoo', 120, 0, true),
(263, 'GLOBAL', 'Third Free Service', 'Tiago', 'CNG', 'Coolant Top Up', 100, 0, true),
(264, 'GLOBAL', 'Third Free Service', 'Tiago', 'CNG', 'Engine Oil', 2159.5, 0, true),
(265, 'GLOBAL', 'Third Free Service', 'Tiago', 'CNG', 'Oil Filter Change', 179, 0, true),
(266, 'GLOBAL', 'Third Free Service', 'Tiago', 'CNG', 'AC Filter', 241, 0, true),
(267, 'GLOBAL', 'Third Free Service', 'Tiago', 'EV', 'Distilled Water', 20, 0, true),
(268, 'GLOBAL', 'Third Free Service', 'Tiago', 'EV', 'Shampoo', 120, 0, true),
(269, 'GLOBAL', 'Third Free Service', 'Tiago', 'EV', 'Coolant Top Up', 212, 0, true),
(270, 'GLOBAL', 'Third Free Service', 'Nexon', 'Petrol', 'Distilled Water', 20, 0, true),
(271, 'GLOBAL', 'Third Free Service', 'Nexon', 'Petrol', 'Shampoo', 120, 0, true),
(272, 'GLOBAL', 'Third Free Service', 'Nexon', 'Petrol', 'Coolant Top Up', 100, 0, true),
(273, 'GLOBAL', 'Third Free Service', 'Nexon', 'Petrol', 'Engine Oil', 2159.5, 0, true),
(274, 'GLOBAL', 'Third Free Service', 'Nexon', 'Petrol', 'Oil Filter Change', 179, 0, true),
(275, 'GLOBAL', 'Third Free Service', 'Nexon', 'Petrol', 'AC Filter', 1027, 0, true),
(276, 'GLOBAL', 'Third Free Service', 'Nexon', 'Petrol', 'Sunroof Greece', 800, 0, true),
(277, 'GLOBAL', 'Third Free Service', 'Nexon', 'Petrol', 'Alignment', 750, 0, true),
(278, 'GLOBAL', 'Third Free Service', 'Nexon', 'Petrol', 'Balancing', 650, 0, true),
(279, 'GLOBAL', 'Third Free Service', 'Nexon', 'Diesel', 'Distilled Water', 20, 0, true),
(280, 'GLOBAL', 'Third Free Service', 'Nexon', 'Diesel', 'Shampoo', 120, 0, true),
(281, 'GLOBAL', 'Third Free Service', 'Nexon', 'Diesel', 'Coolant Top Up', 100, 0, true),
(282, 'GLOBAL', 'Third Free Service', 'Nexon', 'Diesel', 'Engine Oil', 3085, 0, true),
(283, 'GLOBAL', 'Third Free Service', 'Nexon', 'Diesel', 'Oil Filter Change', 192, 0, true),
(284, 'GLOBAL', 'Third Free Service', 'Nexon', 'Diesel', 'AC Filter', 1027, 0, true),
(285, 'GLOBAL', 'Third Free Service', 'Nexon', 'Diesel', 'Sunroof Greece', 800, 0, true),
(286, 'GLOBAL', 'Third Free Service', 'Nexon', 'Diesel', 'Alignment', 750, 0, true),
(287, 'GLOBAL', 'Third Free Service', 'Nexon', 'Diesel', 'Balancing', 650, 0, true),
(288, 'GLOBAL', 'Third Free Service', 'Nexon', 'CNG', 'Distilled Water', 20, 0, true),
(289, 'GLOBAL', 'Third Free Service', 'Nexon', 'CNG', 'Shampoo', 120, 0, true),
(290, 'GLOBAL', 'Third Free Service', 'Nexon', 'CNG', 'Coolant Top Up', 100, 0, true),
(291, 'GLOBAL', 'Third Free Service', 'Nexon', 'CNG', 'Engine Oil', 2159.5, 0, true),
(292, 'GLOBAL', 'Third Free Service', 'Nexon', 'CNG', 'Oil Filter Change', 179, 0, true),
(293, 'GLOBAL', 'Third Free Service', 'Nexon', 'CNG', 'AC Filter', 442, 0, true),
(294, 'GLOBAL', 'Third Free Service', 'Nexon', 'CNG', 'Sunroof Greece', 800, 0, true),
(295, 'GLOBAL', 'Third Free Service', 'Nexon', 'EV', 'Distilled Water', 20, 0, true),
(296, 'GLOBAL', 'Third Free Service', 'Nexon', 'EV', 'Shampoo', 120, 0, true),
(297, 'GLOBAL', 'Third Free Service', 'Nexon', 'EV', 'Coolant Top Up', 212, 0, true),
(298, 'GLOBAL', 'Third Free Service', 'Nexon', 'EV', 'Sunroof Greece', 800, 0, true),
(299, 'GLOBAL', 'Third Free Service', 'Punch', 'Petrol', 'Distilled Water', 20, 0, true),
(300, 'GLOBAL', 'Third Free Service', 'Punch', 'Petrol', 'Shampoo', 120, 0, true),
(301, 'GLOBAL', 'Third Free Service', 'Punch', 'Petrol', 'Coolant Top Up', 100, 0, true),
(302, 'GLOBAL', 'Third Free Service', 'Punch', 'Petrol', 'Engine Oil', 2159.5, 0, true),
(303, 'GLOBAL', 'Third Free Service', 'Punch', 'Petrol', 'Oil Filter Change', 179, 0, true),
(304, 'GLOBAL', 'Third Free Service', 'Punch', 'Petrol', 'AC Filter', 241, 0, true),
(305, 'GLOBAL', 'Third Free Service', 'Punch', 'Petrol', 'Alignment', 737, 0, true),
(306, 'GLOBAL', 'Third Free Service', 'Punch', 'Petrol', 'Balancing', 442, 0, true),
(307, 'GLOBAL', 'Third Free Service', 'Punch', 'Petrol', 'Air Filter', 650, 0, true),
(308, 'GLOBAL', 'Third Free Service', 'Punch', 'Petrol', 'Sunroof Greece', 800, 0, true),
(309, 'GLOBAL', 'Third Free Service', 'Punch', 'CNG', 'Distilled Water', 20, 0, true),
(310, 'GLOBAL', 'Third Free Service', 'Punch', 'CNG', 'Shampoo', 120, 0, true),
(311, 'GLOBAL', 'Third Free Service', 'Punch', 'CNG', 'Coolant Top Up', 100, 0, true),
(312, 'GLOBAL', 'Third Free Service', 'Punch', 'CNG', 'Engine Oil', 2159.5, 0, true),
(313, 'GLOBAL', 'Third Free Service', 'Punch', 'CNG', 'Oil Filter Change', 179, 0, true),
(314, 'GLOBAL', 'Third Free Service', 'Punch', 'CNG', 'AC Filter', 241, 0, true),
(315, 'GLOBAL', 'Third Free Service', 'Punch', 'CNG', 'Sunroof Greece', 800, 0, true),
(316, 'GLOBAL', 'Third Free Service', 'Punch', 'EV', 'Distilled Water', 20, 0, true),
(317, 'GLOBAL', 'Third Free Service', 'Punch', 'EV', 'Shampoo', 120, 0, true),
(318, 'GLOBAL', 'Third Free Service', 'Punch', 'EV', 'Coolant Top Up', 212, 0, true),
(319, 'GLOBAL', 'Third Free Service', 'Punch', 'EV', 'Sunroof Greece', 800, 0, true),
(320, 'GLOBAL', 'Third Free Service', 'Tigor', 'Petrol', 'Distilled Water', 20, 0, true),
(321, 'GLOBAL', 'Third Free Service', 'Tigor', 'Petrol', 'Shampoo', 120, 0, true),
(322, 'GLOBAL', 'Third Free Service', 'Tigor', 'Petrol', 'Coolant Top Up', 100, 0, true),
(323, 'GLOBAL', 'Third Free Service', 'Tigor', 'Petrol', 'Engine Oil', 2159.5, 0, true),
(324, 'GLOBAL', 'Third Free Service', 'Tigor', 'Petrol', 'Oil Filter Change', 179, 0, true),
(325, 'GLOBAL', 'Third Free Service', 'Tigor', 'Petrol', 'AC Filter', 241, 0, true),
(326, 'GLOBAL', 'Third Free Service', 'Tigor', 'Diesel', 'Distilled Water', 20, 0, true),
(327, 'GLOBAL', 'Third Free Service', 'Tigor', 'Diesel', 'Shampoo', 120, 0, true),
(328, 'GLOBAL', 'Third Free Service', 'Tigor', 'Diesel', 'Coolant Top Up', 100, 0, true),
(329, 'GLOBAL', 'Third Free Service', 'Tigor', 'Diesel', 'Engine Oil', 3085, 0, true),
(330, 'GLOBAL', 'Third Free Service', 'Tigor', 'Diesel', 'Oil Filter Change', 192, 0, true),
(331, 'GLOBAL', 'Third Free Service', 'Tigor', 'Diesel', 'AC Filter', 241, 0, true),
(332, 'GLOBAL', 'Third Free Service', 'Tigor', 'CNG', 'Distilled Water', 20, 0, true),
(333, 'GLOBAL', 'Third Free Service', 'Tigor', 'CNG', 'Shampoo', 120, 0, true),
(334, 'GLOBAL', 'Third Free Service', 'Tigor', 'CNG', 'Coolant Top Up', 100, 0, true),
(335, 'GLOBAL', 'Third Free Service', 'Tigor', 'CNG', 'Engine Oil', 2159.5, 0, true),
(336, 'GLOBAL', 'Third Free Service', 'Tigor', 'CNG', 'Oil Filter Change', 179, 0, true),
(337, 'GLOBAL', 'Third Free Service', 'Tigor', 'CNG', 'AC Filter', 241, 0, true),
(338, 'GLOBAL', 'Third Free Service', 'Tigor', 'EV', 'Distilled Water', 20, 0, true),
(339, 'GLOBAL', 'Third Free Service', 'Tigor', 'EV', 'Shampoo', 120, 0, true),
(340, 'GLOBAL', 'Third Free Service', 'Tigor', 'EV', 'Coolant Top Up', 212, 0, true),
(341, 'GLOBAL', 'Third Free Service', 'Curvv', 'Petrol', 'Shampoo', 120, 0, true),
(342, 'GLOBAL', 'Third Free Service', 'Curvv', 'Petrol', 'Coolant Top Up', 100, 0, true),
(343, 'GLOBAL', 'Third Free Service', 'Curvv', 'Petrol', 'Engine Oil', 2159.5, 0, true),
(344, 'GLOBAL', 'Third Free Service', 'Curvv', 'Petrol', 'Oil Filter Change', 0, 0, true),
(345, 'GLOBAL', 'Third Free Service', 'Curvv', 'Petrol', 'AC Filter', 1027, 0, true),
(346, 'GLOBAL', 'Third Free Service', 'Curvv', 'Petrol', 'Sunroof Greece', 800, 0, true),
(347, 'GLOBAL', 'Third Free Service', 'Curvv', 'Diesel', 'Distilled Water', 20, 0, true),
(348, 'GLOBAL', 'Third Free Service', 'Curvv', 'Diesel', 'Shampoo', 120, 0, true),
(349, 'GLOBAL', 'Third Free Service', 'Curvv', 'Diesel', 'Coolant Top Up', 100, 0, true),
(350, 'GLOBAL', 'Third Free Service', 'Curvv', 'Diesel', 'Engine Oil', 3085, 0, true),
(351, 'GLOBAL', 'Third Free Service', 'Curvv', 'Diesel', 'Oil Filter Change', 212, 0, true),
(352, 'GLOBAL', 'Third Free Service', 'Curvv', 'Diesel', 'AC Filter', 1027, 0, true),
(353, 'GLOBAL', 'Third Free Service', 'Curvv', 'Diesel', 'Sunroof Greece', 800, 0, true),
(354, 'GLOBAL', 'Third Free Service', 'Curvv', 'EV', 'Distilled Water', 20, 0, true),
(355, 'GLOBAL', 'Third Free Service', 'Curvv', 'EV', 'Shampoo', 120, 0, true),
(356, 'GLOBAL', 'Third Free Service', 'Curvv', 'EV', 'Coolant Top Up', 212, 0, true),
(357, 'GLOBAL', 'Third Free Service', 'Curvv', 'EV', 'Sunroof Greece', 800, 0, true),
(358, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Distilled Water', 20, 0, true),
(359, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Shampoo', 120, 0, true),
(360, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Coolant Top Up', 100, 0, true),
(361, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Engine Oil', 5295, 0, true),
(362, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Oil Filter Change', 792, 0, true),
(363, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Pollen Filter', 1582, 0, true),
(364, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Sunroof Greece', 800, 0, true),
(365, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Balancing', 600, 0, true),
(366, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Diesel Filter', 3000, 0, true),
(367, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'air Filter', 1000, 0, true),
(368, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Alignment', 1200, 0, true),
(369, 'GLOBAL', 'Third Free Service', 'Harrier', 'Diesel', 'Def', 620, 0, true),
(370, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Distilled Water', 20, 0, true),
(371, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Shampoo', 120, 0, true),
(372, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Coolant Top Up', 100, 0, true),
(373, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Engine Oil', 5295, 0, true),
(374, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Oil Filter Change', 792, 0, true),
(375, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Pollen Filter', 1581, 0, true),
(376, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Sunroof Greece', 800, 0, true),
(377, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Balancing', 600, 0, true),
(378, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Diesel Filter', 3000, 0, true),
(379, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'air Filter', 1000, 0, true),
(380, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Alignment', 1200, 0, true),
(381, 'GLOBAL', 'Third Free Service', 'Safari', 'Diesel', 'Def', 620, 0, true),
(382, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Distilled Water', 20, 2160, true),
(383, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Shampoo', 120, 2160, true),
(384, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Oil Filter Change', 179, 2160, true),
(385, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Gear Oil', 832, 2160, true),
(386, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Air Filter', 519, 2160, true),
(387, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'AC Filter', 347, 2160, true),
(388, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Alignment', 750, 2160, true),
(389, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Balancing', 580, 2160, true),
(390, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Engine Oil', 2159.5, 2160, true),
(391, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Fuel Filter', 443, 2160, true),
(392, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Break oil', 224, 2160, true),
(393, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Sunroof Greece', 800, 2160, true),
(394, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Service Kit', 1467, 2160, true),
(395, 'GLOBAL', 'Paid Service', 'Altroz', 'Petrol', 'Spark Plug', 540, 2160, true),
(396, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Distilled Water', 20, 2160, true),
(397, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Shampoo', 120, 2160, true),
(398, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Oil Filter Change', 212, 2160, true),
(399, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Gear Oil', 832, 2160, true),
(400, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Air Filter', 406, 2160, true),
(401, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'AC Filter', 347, 2160, true),
(402, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Alignment', 750, 2160, true),
(403, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Balancing', 580, 2160, true),
(404, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Engine Oil', 3085, 2160, true),
(405, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Fuel Filter', 944, 2160, true),
(406, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Break oil', 224, 2160, true),
(407, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Sunroof Greece', 800, 2160, true),
(408, 'GLOBAL', 'Paid Service', 'Altroz', 'Diesel', 'Service Kit', 1807, 2160, true),
(409, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Distilled Water', 20, 2160, true),
(410, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Shampoo', 120, 2160, true),
(411, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Oil Filter Change', 179, 2160, true),
(412, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Gear Oil', 832, 2160, true),
(413, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Air Filter', 861, 2160, true),
(414, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'AC Filter', 347, 2160, true),
(415, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Alignment', 750, 2160, true),
(416, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Balancing', 580, 2160, true),
(417, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Engine Oil', 2159.5, 2160, true),
(418, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Fuel Filter', 443, 2160, true),
(419, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Break oil', 224, 2160, true),
(420, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Sunroof Greece', 800, 2160, true),
(421, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Service Kit', 1467, 2160, true),
(422, 'GLOBAL', 'Paid Service', 'Altroz', 'CNG', 'Spark Plug', 540, 2160, true),
(423, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Distilled Water', 20, 2160, true),
(424, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Shampoo', 120, 2160, true),
(425, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Oil Filter Change', 179, 2160, true),
(426, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Gear Oil', 832, 2160, true),
(427, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Air Filter', 509, 2160, true),
(428, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'AC Filter', 241, 2160, true),
(429, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Alignment', 680, 2160, true),
(430, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Balancing', 580, 2160, true),
(431, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Engine Oil', 2159.5, 2160, true),
(432, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Fuel Filter', 443, 2160, true),
(433, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Break oil', 224, 2160, true),
(434, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Service Kit', 1134, 2160, true),
(435, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Spark Plug', 540, 2160, true),
(436, 'GLOBAL', 'Paid Service', 'Tiago', 'Petrol', 'Coolant Top Up', 950, 0, true),
(437, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Distilled Water', 20, 2160, true),
(438, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Shampoo', 120, 2160, true),
(439, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Oil Filter Change', 212, 2160, true),
(440, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Gear Oil', 832, 2160, true),
(441, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Air Filter', 679, 2160, true),
(442, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'AC Filter', 241, 2160, true),
(443, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Alignment', 680, 2160, true),
(444, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Balancing', 580, 2160, true),
(445, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Engine Oil', 3085, 2160, true),
(446, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Fuel Filter', 944, 2160, true),
(447, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Break oil', 224, 2160, true),
(448, 'GLOBAL', 'Paid Service', 'Tiago', 'Diesel', 'Service Kit', 4253, 2160, true),
(449, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Distilled Water', 20, 2160, true),
(450, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Shampoo', 120, 2160, true),
(451, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Oil Filter Change', 179, 2160, true),
(452, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Gear Oil', 832, 2160, true),
(453, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Air Filter', 861, 2160, true),
(454, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'AC Filter', 241, 2160, true),
(455, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Alignment', 680, 2160, true),
(456, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Balancing', 580, 2160, true),
(457, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Engine Oil', 2159.5, 2160, true),
(458, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Fuel Filter', 443, 2160, true),
(459, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Break oil', 224, 2160, true),
(460, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Service Kit', 1467, 2160, true),
(461, 'GLOBAL', 'Paid Service', 'Tiago', 'CNG', 'Spark Plug', 540, 2160, true),
(462, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Distilled Water', 20, 2160, true),
(463, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Shampoo', 120, 2160, true),
(464, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Oil Filter Change', 0, 2160, true),
(465, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Gear Oil', 1761, 2160, true),
(466, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Air Filter', 861, 2160, true),
(467, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'AC Filter', 241, 2160, true),
(468, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Alignment', 680, 2160, true),
(469, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Balancing', 580, 2160, true),
(470, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Fuel Filter', 0, 2160, true),
(471, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Break oil', 224, 2160, true),
(472, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Service Kit', 0, 2160, true),
(473, 'GLOBAL', 'Paid Service', 'Tiago', 'EV', 'Spark Plug', 0, 2160, true),
(474, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Distilled Water', 20, 2160, true),
(475, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Shampoo', 120, 2160, true),
(476, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Oil Filter Change', 179, 2160, true),
(477, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Gear Oil', 832, 2160, true),
(478, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Air Filter', 527, 2160, true),
(479, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'AC Filter', 1027, 2160, true),
(480, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Alignment', 680, 2160, true),
(481, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Balancing', 580, 2160, true),
(482, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Engine Oil', 2159.5, 2160, true),
(483, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Fuel Filter', 443, 2160, true),
(484, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Break oil', 224, 2160, true),
(485, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Sunroof Greece', 800, 2160, true),
(486, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Service Kit', 2600, 2160, true),
(487, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Spark Plug', 1062, 2160, true),
(488, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Pollen Filter', 1027, 2160, true),
(489, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Comby Filter', 1027, 2160, true),
(490, 'GLOBAL', 'Paid Service', 'Nexon', 'Petrol', 'Coolant', 1000, 2160, true),
(491, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Distilled Water', 20, 2160, true),
(492, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Shampoo', 120, 2160, true),
(493, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Oil Filter Change', 212, 2160, true),
(494, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Gear Oil', 832, 2160, true),
(495, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Air Filter', 539, 2160, true),
(496, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'AC Filter', 1027, 2160, true),
(497, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Alignment', 680, 2160, true),
(498, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Balancing', 580, 2160, true),
(499, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Engine Oil', 3085, 2160, true),
(500, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Fuel Filter', 944, 2160, true),
(501, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Break oil', 224, 2160, true),
(502, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Sunroof Greece', 800, 2160, true),
(503, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Service Kit', 2520, 2160, true),
(504, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Pollen Filter', 1027, 2160, true),
(505, 'GLOBAL', 'Paid Service', 'Nexon', 'Diesel', 'Comby Filter', 1027, 2160, true),
(506, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Distilled Water', 20, 2160, true),
(507, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Shampoo', 120, 2160, true),
(508, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Oil Filter Change', 179, 2160, true),
(509, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Gear Oil', 832, 2160, true),
(510, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Air Filter', 527, 2160, true),
(511, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'AC Filter', 442, 2160, true),
(512, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Alignment', 680, 2160, true),
(513, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Balancing', 580, 2160, true),
(514, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Engine Oil', 2159.5, 2160, true),
(515, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Fuel Filter', 443, 2160, true),
(516, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Break oil', 224, 2160, true),
(517, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Sunroof Greece', 800, 2160, true),
(518, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Service Kit', 2600, 2160, true),
(519, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Spark Plug', 1062, 2160, true),
(520, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Pollen Filter', 1027, 2160, true),
(521, 'GLOBAL', 'Paid Service', 'Nexon', 'CNG', 'Comby Filter', 1027, 2160, true),
(522, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Distilled Water', 20, 2160, true),
(523, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Shampoo', 120, 2160, true),
(524, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Oil Filter Change', 0, 2160, true),
(525, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Gear Oil', 1851, 2160, true),
(526, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Air Filter', 527, 2160, true),
(527, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'AC Filter', 442, 2160, true),
(528, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Alignment', 680, 2160, true),
(529, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Balancing', 580, 2160, true),
(530, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Fuel Filter', 0, 2160, true),
(531, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Break oil', 224, 2160, true),
(532, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Sunroof Greece', 800, 2160, true),
(533, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Service Kit', 0, 2160, true),
(534, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Spark Plug', 0, 2160, true),
(535, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Pollen Filter', 1027, 2160, true),
(536, 'GLOBAL', 'Paid Service', 'Nexon', 'EV', 'Comby Filter', 1027, 2160, true),
(537, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Distilled Water', 20, 2160, true),
(538, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Shampoo', 120, 2160, true),
(539, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Oil Filter Change', 179, 2160, true),
(540, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Gear Oil', 832, 2160, true),
(541, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Air Filter', 509, 2160, true),
(542, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'AC Filter', 241, 2160, true),
(543, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Alignment', 680, 2160, true),
(544, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Balancing', 580, 2160, true),
(545, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Engine Oil', 2159.5, 2160, true),
(546, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Fuel Filter', 443, 2160, true),
(547, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Break oil', 224, 2160, true),
(548, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Sunroof Greece', 800, 2160, true),
(549, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Service Kit', 1467, 2160, true),
(550, 'GLOBAL', 'Paid Service', 'Punch', 'Petrol', 'Spark Plug', 540, 2160, true),
(551, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Distilled Water', 20, 2160, true),
(552, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Shampoo', 120, 2160, true),
(553, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Oil Filter Change', 179, 2160, true),
(554, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Gear Oil', 832, 2160, true),
(555, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Air Filter', 861, 2160, true),
(556, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'AC Filter', 241, 2160, true),
(557, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Alignment', 680, 2160, true),
(558, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Balancing', 580, 2160, true),
(559, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Engine Oil', 2159.5, 2160, true),
(560, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Fuel Filter', 443, 2160, true),
(561, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Break oil', 224, 2160, true),
(562, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Sunroof Greece', 800, 2160, true),
(563, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Service Kit', 1467, 2160, true),
(564, 'GLOBAL', 'Paid Service', 'Punch', 'CNG', 'Spark Plug', 540, 2160, true),
(565, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Distilled Water', 20, 2160, true),
(566, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Shampoo', 120, 2160, true),
(567, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Oil Filter Change', 0, 2160, true),
(568, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Gear Oil', 1762, 2160, true),
(569, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Air Filter', 861, 2160, true),
(570, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'AC Filter', 241, 2160, true),
(571, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Alignment', 680, 2160, true),
(572, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Balancing', 580, 2160, true),
(573, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Fuel Filter', 0, 2160, true),
(574, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Break oil', 224, 2160, true),
(575, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Sunroof Greece', 800, 2160, true),
(576, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Service Kit', 0, 2160, true),
(577, 'GLOBAL', 'Paid Service', 'Punch', 'EV', 'Spark Plug', 0, 2160, true),
(578, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Distilled Water', 20, 2160, true),
(579, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Shampoo', 120, 2160, true),
(580, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Oil Filter Change', 179, 2160, true),
(581, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Gear Oil', 832, 2160, true),
(582, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Air Filter', 509, 2160, true),
(583, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'AC Filter', 241, 2160, true),
(584, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Alignment', 680, 2160, true),
(585, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Balancing', 580, 2160, true),
(586, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Engine Oil', 2159.5, 2160, true),
(587, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Fuel Filter', 443, 2160, true),
(588, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Break oil', 224, 2160, true),
(589, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Service Kit', 1134, 2160, true),
(590, 'GLOBAL', 'Paid Service', 'Tigor', 'Petrol', 'Spark Plug', 540, 2160, true),
(591, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Distilled Water', 20, 2160, true),
(592, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Shampoo', 120, 2160, true),
(593, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Oil Filter Change', 212, 2160, true),
(594, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Gear Oil', 832, 2160, true),
(595, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Air Filter', 679, 2160, true),
(596, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'AC Filter', 241, 2160, true),
(597, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Alignment', 680, 2160, true),
(598, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Balancing', 580, 2160, true),
(599, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Engine Oil', 3085, 2160, true),
(600, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Fuel Filter', 944, 2160, true),
(601, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Break oil', 224, 2160, true),
(602, 'GLOBAL', 'Paid Service', 'Tigor', 'Diesel', 'Service Kit', 4253, 2160, true),
(603, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Distilled Water', 20, 2160, true),
(604, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Shampoo', 120, 2160, true),
(605, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Oil Filter Change', 179, 2160, true),
(606, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Gear Oil', 832, 2160, true),
(607, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Air Filter', 861, 2160, true),
(608, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'AC Filter', 241, 2160, true),
(609, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Alignment', 680, 2160, true),
(610, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Balancing', 580, 2160, true),
(611, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Engine Oil', 2159.5, 2160, true),
(612, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Fuel Filter', 443, 2160, true),
(613, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Break oil', 224, 2160, true),
(614, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Service Kit', 1467, 2160, true),
(615, 'GLOBAL', 'Paid Service', 'Tigor', 'CNG', 'Spark Plug', 540, 2160, true),
(616, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Distilled Water', 20, 2160, true),
(617, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Shampoo', 120, 2160, true),
(618, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Oil Filter Change', 0, 2160, true),
(619, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Gear Oil', 1762, 2160, true),
(620, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Air Filter', 861, 2160, true),
(621, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'AC Filter', 241, 2160, true),
(622, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Alignment', 680, 2160, true),
(623, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Balancing', 580, 2160, true),
(624, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Fuel Filter', 0, 2160, true),
(625, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Break oil', 224, 2160, true),
(626, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Service Kit', 0, 2160, true),
(627, 'GLOBAL', 'Paid Service', 'Tigor', 'EV', 'Spark Plug', 0, 2160, true),
(628, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Distilled Water', 20, 1510, true),
(629, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Shampoo', 120, 1510, true),
(630, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Oil Filter Change', 179, 1510, true),
(631, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Gear Oil', 832, 1510, true),
(632, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Air Filter', 527, 1510, true),
(633, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'AC Filter', 1027, 1510, true),
(634, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Alignment', 750, 1510, true),
(635, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Balancing', 0, 1510, true),
(636, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Engine Oil', 2159.5, 1510, true),
(637, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Fuel Filter', 443, 1510, true),
(638, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Break oil', 224, 1510, true),
(639, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Sunroof Greece', 800, 1510, true),
(640, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Service Kit', 2600, 1510, true),
(641, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Spark Plug', 0, 1510, true),
(642, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Pollen Filter', 0, 1510, true),
(643, 'GLOBAL', 'Paid Service', 'Curvv', 'Petrol', 'Comby Filter', 1027, 1510, true),
(644, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Distilled Water', 20, 1510, true),
(645, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Shampoo', 120, 1510, true),
(646, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Oil Filter Change', 212, 1510, true),
(647, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Gear Oil', 832, 1510, true),
(648, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Air Filter', 539, 1510, true),
(649, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'AC Filter', 1027, 1510, true),
(650, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Alignment', 750, 1510, true),
(651, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Balancing', 0, 1510, true),
(652, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Engine Oil', 3085, 1510, true),
(653, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Fuel Filter', 944, 1510, true),
(654, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Break oil', 224, 1510, true),
(655, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Sunroof Greece', 800, 1510, true),
(656, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Service Kit', 2520, 1510, true),
(657, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Pollen Filter', 0, 1510, true),
(658, 'GLOBAL', 'Paid Service', 'Curvv', 'Diesel', 'Comby Filter', 1027, 1510, true),
(659, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Distilled Water', 20, 2335, true),
(660, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Shampoo', 120, 2335, true),
(661, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Oil Filter Change', 0, 2335, true),
(662, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Gear Oil', 1762, 2335, true),
(663, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Air Filter', 539, 2335, true),
(664, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'AC Filter', 1027, 2335, true),
(665, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Alignment', 750, 2335, true),
(666, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Balancing', 0, 2335, true),
(667, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Fuel Filter', 0, 2335, true),
(668, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Break oil', 224, 2335, true),
(669, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Sunroof Greece', 800, 2335, true),
(670, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Service Kit', 0, 2335, true),
(671, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Spark Plug', 0, 2335, true),
(672, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Pollen Filter', 0, 2335, true),
(673, 'GLOBAL', 'Paid Service', 'Curvv', 'EV', 'Comby Filter', 1027, 2335, true),
(674, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Balancing', 600, 3960, true),
(675, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Shampoo', 120, 3960, true),
(676, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Oil Filter Change', 792, 3960, true),
(677, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Gear Oil', 3715, 3960, true),
(678, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Air Filter', 906, 3960, true),
(679, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Alignment', 1328, 3960, true),
(680, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Engine Oil', 5295, 3960, true),
(681, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Fuel Filter', 2654, 3960, true),
(682, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Break oil', 224, 3960, true),
(683, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Sunroof Greece', 800, 3960, true),
(684, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Service Kit', 5532, 3960, true),
(685, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Pollen Filter', 1581, 3960, true),
(686, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Comby Filter', 1581, 3960, true),
(687, 'GLOBAL', 'Paid Service', 'Harrier', 'Diesel', 'Def', 620, 3960, true),
(688, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Distilled Water', 20, 3983, true),
(689, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Shampoo', 120, 3983, true),
(690, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Oil Filter Change', 792, 3983, true),
(691, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Gear Oil', 3715, 3983, true),
(692, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Air Filter', 906, 3983, true),
(693, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Alignment', 1328, 3983, true),
(694, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Balancing', 580, 3983, true),
(695, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Engine Oil', 5295, 3983, true),
(696, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Fuel Filter', 2654, 3983, true),
(697, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Break oil', 224, 3983, true),
(698, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Sunroof Greece', 800, 3983, true),
(699, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Service Kit', 5532, 3983, true),
(700, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Pollen Filter', 1581, 3983, true),
(701, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Comby Filter', 1581, 3983, true),
(702, 'GLOBAL', 'Paid Service', 'Safari', 'Diesel', 'Def', 620, 3983, true),
(703, 'GLOBAL', 'Running Repairs', 'Altroz', 'Petrol', 'Tyre Issue', 0, 0, true),
(704, 'GLOBAL', 'Running Repairs', 'Altroz', 'Petrol', 'Battery Issue', 0, 0, true),
(705, 'GLOBAL', 'Running Repairs', 'Altroz', 'Petrol', 'Updation', 0, 0, true),
(706, 'GLOBAL', 'Running Repairs', 'Altroz', 'Diesel', 'Tyre Issue', 0, 0, true),
(707, 'GLOBAL', 'Running Repairs', 'Altroz', 'Diesel', 'Battery Issue', 0, 0, true),
(708, 'GLOBAL', 'Running Repairs', 'Altroz', 'Diesel', 'Updation', 0, 0, true),
(709, 'GLOBAL', 'Running Repairs', 'Altroz', 'CNG', 'Tyre Issue', 0, 0, true),
(710, 'GLOBAL', 'Running Repairs', 'Altroz', 'CNG', 'Battery Issue', 0, 0, true),
(711, 'GLOBAL', 'Running Repairs', 'Altroz', 'CNG', 'Updation', 0, 0, true),
(712, 'GLOBAL', 'Running Repairs', 'Tiago', 'Petrol', 'Tyre Issue', 0, 0, true),
(713, 'GLOBAL', 'Running Repairs', 'Tiago', 'Petrol', 'Battery Issue', 0, 0, true),
(714, 'GLOBAL', 'Running Repairs', 'Tiago', 'Petrol', 'Updation', 0, 0, true),
(715, 'GLOBAL', 'Running Repairs', 'Tiago', 'Diesel', 'Tyre Issue', 0, 0, true),
(716, 'GLOBAL', 'Running Repairs', 'Tiago', 'Diesel', 'Battery Issue', 0, 0, true),
(717, 'GLOBAL', 'Running Repairs', 'Tiago', 'Diesel', 'Updation', 0, 0, true),
(718, 'GLOBAL', 'Running Repairs', 'Tiago', 'CNG', 'Tyre Issue', 0, 0, true),
(719, 'GLOBAL', 'Running Repairs', 'Tiago', 'CNG', 'Battery Issue', 0, 0, true),
(720, 'GLOBAL', 'Running Repairs', 'Tiago', 'CNG', 'Updation', 0, 0, true),
(721, 'GLOBAL', 'Running Repairs', 'Tiago', 'EV', 'Tyre Issue', 0, 0, true),
(722, 'GLOBAL', 'Running Repairs', 'Tiago', 'EV', 'Battery Issue', 0, 0, true),
(723, 'GLOBAL', 'Running Repairs', 'Tiago', 'EV', 'Updation', 0, 0, true),
(724, 'GLOBAL', 'Running Repairs', 'Nexon', 'Petrol', 'Tyre Issue', 0, 0, true),
(725, 'GLOBAL', 'Running Repairs', 'Nexon', 'Petrol', 'Battery Issue', 0, 0, true),
(726, 'GLOBAL', 'Running Repairs', 'Nexon', 'Petrol', 'Updation', 0, 0, true),
(727, 'GLOBAL', 'Running Repairs', 'Nexon', 'Diesel', 'Tyre Issue', 0, 0, true),
(728, 'GLOBAL', 'Running Repairs', 'Nexon', 'Diesel', 'Battery Issue', 0, 0, true),
(729, 'GLOBAL', 'Running Repairs', 'Nexon', 'Diesel', 'Updation', 0, 0, true),
(730, 'GLOBAL', 'Running Repairs', 'Nexon', 'CNG', 'Tyre Issue', 0, 0, true),
(731, 'GLOBAL', 'Running Repairs', 'Nexon', 'CNG', 'Battery Issue', 0, 0, true),
(732, 'GLOBAL', 'Running Repairs', 'Nexon', 'CNG', 'Updation', 0, 0, true),
(733, 'GLOBAL', 'Running Repairs', 'Nexon', 'EV', 'Tyre Issue', 0, 0, true),
(734, 'GLOBAL', 'Running Repairs', 'Nexon', 'EV', 'Battery Issue', 0, 0, true),
(735, 'GLOBAL', 'Running Repairs', 'Nexon', 'EV', 'Updation', 0, 0, true),
(736, 'GLOBAL', 'Running Repairs', 'Punch', 'Petrol', 'Tyre Issue', 0, 0, true),
(737, 'GLOBAL', 'Running Repairs', 'Punch', 'Petrol', 'Battery Issue', 0, 0, true),
(738, 'GLOBAL', 'Running Repairs', 'Punch', 'Petrol', 'Updation', 0, 0, true),
(739, 'GLOBAL', 'Running Repairs', 'Punch', 'CNG', 'Tyre Issue', 0, 0, true),
(740, 'GLOBAL', 'Running Repairs', 'Punch', 'CNG', 'Battery Issue', 0, 0, true),
(741, 'GLOBAL', 'Running Repairs', 'Punch', 'CNG', 'Updation', 0, 0, true),
(742, 'GLOBAL', 'Running Repairs', 'Punch', 'EV', 'Tyre Issue', 0, 0, true),
(743, 'GLOBAL', 'Running Repairs', 'Punch', 'EV', 'Battery Issue', 0, 0, true),
(744, 'GLOBAL', 'Running Repairs', 'Punch', 'EV', 'Updation', 0, 0, true),
(745, 'GLOBAL', 'Running Repairs', 'Tigor', 'Petrol', 'Tyre Issue', 0, 0, true),
(746, 'GLOBAL', 'Running Repairs', 'Tigor', 'Petrol', 'Battery Issue', 0, 0, true),
(747, 'GLOBAL', 'Running Repairs', 'Tigor', 'Petrol', 'Updation', 0, 0, true),
(748, 'GLOBAL', 'Running Repairs', 'Tigor', 'Diesel', 'Tyre Issue', 0, 0, true),
(749, 'GLOBAL', 'Running Repairs', 'Tigor', 'Diesel', 'Battery Issue', 0, 0, true),
(750, 'GLOBAL', 'Running Repairs', 'Tigor', 'Diesel', 'Updation', 0, 0, true),
(751, 'GLOBAL', 'Running Repairs', 'Tigor', 'CNG', 'Tyre Issue', 0, 0, true),
(752, 'GLOBAL', 'Running Repairs', 'Tigor', 'CNG', 'Battery Issue', 0, 0, true),
(753, 'GLOBAL', 'Running Repairs', 'Tigor', 'CNG', 'Updation', 0, 0, true),
(754, 'GLOBAL', 'Running Repairs', 'Tigor', 'EV', 'Tyre Issue', 0, 0, true),
(755, 'GLOBAL', 'Running Repairs', 'Tigor', 'EV', 'Battery Issue', 0, 0, true),
(756, 'GLOBAL', 'Running Repairs', 'Tigor', 'EV', 'Updation', 0, 0, true),
(757, 'GLOBAL', 'Running Repairs', 'Curvv', 'Petrol', 'Tyre Issue', 0, 0, true),
(758, 'GLOBAL', 'Running Repairs', 'Curvv', 'Petrol', 'Battery Issue', 0, 0, true),
(759, 'GLOBAL', 'Running Repairs', 'Curvv', 'Petrol', 'Updation', 0, 0, true),
(760, 'GLOBAL', 'Running Repairs', 'Curvv', 'Diesel', 'Tyre Issue', 0, 0, true),
(761, 'GLOBAL', 'Running Repairs', 'Curvv', 'Diesel', 'Battery Issue', 0, 0, true),
(762, 'GLOBAL', 'Running Repairs', 'Curvv', 'Diesel', 'Updation', 0, 0, true),
(763, 'GLOBAL', 'Running Repairs', 'Curvv', 'EV', 'Tyre Issue', 0, 0, true),
(764, 'GLOBAL', 'Running Repairs', 'Curvv', 'EV', 'Battery Issue', 0, 0, true),
(765, 'GLOBAL', 'Running Repairs', 'Curvv', 'EV', 'Updation', 0, 0, true),
(766, 'GLOBAL', 'Running Repairs', 'Harrier', 'Diesel', 'Tyre Issue', 0, 0, true),
(767, 'GLOBAL', 'Running Repairs', 'Harrier', 'Diesel', 'Def Refill', 0, 0, true),
(768, 'GLOBAL', 'Running Repairs', 'Harrier', 'Diesel', 'Battery Issue', 0, 0, true),
(769, 'GLOBAL', 'Running Repairs', 'Harrier', 'Diesel', 'Updation', 0, 0, true),
(770, 'GLOBAL', 'Running Repairs', 'Safari', 'Diesel', 'Tyre Issue', 0, 0, true),
(771, 'GLOBAL', 'Running Repairs', 'Safari', 'Diesel', 'Def Refill', 0, 0, true),
(772, 'GLOBAL', 'Running Repairs', 'Safari', 'Diesel', 'Battery Issue', 0, 0, true),
(773, 'GLOBAL', 'Running Repairs', 'Safari', 'Diesel', 'Updation', 0, 0, true),
(774, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'Petrol', 'Distilled Water', 20, 1080, true),
(775, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'Petrol', 'Shampoo', 120, 1080, true),
(776, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'Petrol', 'Coolant Top Up', 100, 1080, true),
(777, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'Petrol', 'Oil Filter Change', 179, 1080, true),
(778, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'Petrol', 'Sunroof Greece', 800, 1080, true),
(779, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'Diesel', 'Distilled Water', 20, 1080, true),
(780, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'Diesel', 'Shampoo', 120, 1080, true),
(781, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'Diesel', 'Coolant Top Up', 100, 1080, true),
(782, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'Diesel', 'Oil Filter Change', 212, 1080, true),
(783, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'Diesel', 'Sunroof Greece', 800, 1080, true),
(784, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'CNG', 'Distilled Water', 20, 1080, true),
(785, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'CNG', 'Shampoo', 120, 1080, true),
(786, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'CNG', 'Coolant Top Up', 100, 1080, true),
(787, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'CNG', 'Oil Filter Change', 179, 1080, true),
(788, 'GLOBAL', 'Mini Paid Service', 'Altroz', 'CNG', 'Sunroof Greece', 800, 1080, true),
(789, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'Petrol', 'Distilled Water', 20, 1080, true),
(790, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'Petrol', 'Shampoo', 120, 1080, true),
(791, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'Petrol', 'Coolant Top Up', 100, 1080, true),
(792, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'Petrol', 'Oil Filter Change', 179, 1080, true),
(793, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'Diesel', 'Distilled Water', 20, 1080, true),
(794, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'Diesel', 'Shampoo', 120, 1080, true),
(795, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'Diesel', 'Coolant Top Up', 100, 1080, true),
(796, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'Diesel', 'Oil Filter Change', 212, 1080, true),
(797, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'CNG', 'Distilled Water', 20, 1080, true),
(798, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'CNG', 'Shampoo', 120, 1080, true),
(799, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'CNG', 'Coolant Top Up', 100, 1080, true),
(800, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'CNG', 'Oil Filter Change', 179, 1080, true),
(801, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'EV', 'Distilled Water', 20, 1080, true),
(802, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'EV', 'Shampoo', 120, 1080, true),
(803, 'GLOBAL', 'Mini Paid Service', 'Tiago', 'EV', 'Coolant Top Up', 212, 1080, true),
(804, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Petrol', 'Distilled Water', 20, 1080, true),
(805, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Petrol', 'Shampoo', 120, 1080, true),
(806, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Petrol', 'Coolant Top Up', 100, 1080, true),
(807, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Petrol', 'Oil Filter Change', 179, 1080, true),
(808, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Petrol', 'Alignment', 750, 1080, true),
(809, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Petrol', 'Balancing', 500, 1080, true),
(810, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Petrol', 'Sunroof Greece', 800, 1080, true),
(811, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Diesel', 'Distilled Water', 20, 1080, true),
(812, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Diesel', 'Shampoo', 120, 1080, true),
(813, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Diesel', 'Coolant Top Up', 100, 1080, true),
(814, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Diesel', 'Oil Filter Change', 212, 1080, true),
(815, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'Diesel', 'Sunroof Greece', 800, 1080, true),
(816, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'CNG', 'Distilled Water', 20, 1080, true),
(817, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'CNG', 'Shampoo', 120, 1080, true),
(818, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'CNG', 'Coolant Top Up', 100, 1080, true),
(819, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'CNG', 'Oil Filter Change', 179, 1080, true),
(820, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'CNG', 'Sunroof Greece', 800, 1080, true),
(821, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'EV', 'Distilled Water', 20, 1080, true),
(822, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'EV', 'Shampoo', 120, 1080, true),
(823, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'EV', 'Coolant Top Up', 212, 1080, true),
(824, 'GLOBAL', 'Mini Paid Service', 'Nexon', 'EV', 'Sunroof Greece', 800, 1080, true),
(825, 'GLOBAL', 'Mini Paid Service', 'Punch', 'Petrol', 'Distilled Water', 20, 1080, true),
(826, 'GLOBAL', 'Mini Paid Service', 'Punch', 'Petrol', 'Shampoo', 120, 1080, true),
(827, 'GLOBAL', 'Mini Paid Service', 'Punch', 'Petrol', 'Coolant Top Up', 100, 1080, true),
(828, 'GLOBAL', 'Mini Paid Service', 'Punch', 'Petrol', 'Oil Filter Change', 179, 1080, true),
(829, 'GLOBAL', 'Mini Paid Service', 'Punch', 'Petrol', 'Sunroof Greece', 800, 1080, true),
(830, 'GLOBAL', 'Mini Paid Service', 'Punch', 'CNG', 'Distilled Water', 20, 1080, true),
(831, 'GLOBAL', 'Mini Paid Service', 'Punch', 'CNG', 'Shampoo', 120, 1080, true),
(832, 'GLOBAL', 'Mini Paid Service', 'Punch', 'CNG', 'Coolant Top Up', 100, 1080, true),
(833, 'GLOBAL', 'Mini Paid Service', 'Punch', 'CNG', 'Oil Filter Change', 179, 1080, true),
(834, 'GLOBAL', 'Mini Paid Service', 'Punch', 'CNG', 'Sunroof Greece', 800, 1080, true),
(835, 'GLOBAL', 'Mini Paid Service', 'Punch', 'EV', 'Distilled Water', 20, 1080, true),
(836, 'GLOBAL', 'Mini Paid Service', 'Punch', 'EV', 'Shampoo', 120, 1080, true),
(837, 'GLOBAL', 'Mini Paid Service', 'Punch', 'EV', 'Coolant Top Up', 212, 1080, true),
(838, 'GLOBAL', 'Mini Paid Service', 'Punch', 'EV', 'Sunroof Greece', 800, 1080, true),
(839, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'Petrol', 'Distilled Water', 20, 1080, true),
(840, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'Petrol', 'Shampoo', 120, 1080, true),
(841, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'Petrol', 'Coolant Top Up', 100, 1080, true),
(842, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'Petrol', 'Oil Filter Change', 179, 1080, true),
(843, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'Diesel', 'Distilled Water', 20, 1080, true),
(844, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'Diesel', 'Shampoo', 120, 1080, true),
(845, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'Diesel', 'Coolant Top Up', 100, 1080, true),
(846, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'Diesel', 'Oil Filter Change', 212, 1080, true),
(847, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'CNG', 'Distilled Water', 20, 1080, true),
(848, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'CNG', 'Shampoo', 120, 1080, true),
(849, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'CNG', 'Coolant Top Up', 100, 1080, true),
(850, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'CNG', 'Oil Filter Change', 179, 1080, true),
(851, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'EV', 'Distilled Water', 20, 1080, true),
(852, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'EV', 'Shampoo', 120, 1080, true),
(853, 'GLOBAL', 'Mini Paid Service', 'Tigor', 'EV', 'Coolant Top Up', 212, 1080, true),
(854, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'Petrol', 'Shampoo', 120, 755, true),
(855, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'Petrol', 'Coolant Top Up', 100, 755, true),
(856, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'Petrol', 'Oil Filter Change', 179, 755, true),
(857, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'Petrol', 'Sunroof Greece', 800, 755, true),
(858, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'Diesel', 'Distilled Water', 20, 755, true),
(859, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'Diesel', 'Shampoo', 120, 755, true),
(860, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'Diesel', 'Coolant Top Up', 100, 755, true),
(861, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'Diesel', 'Oil Filter Change', 212, 755, true),
(862, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'Diesel', 'Sunroof Greece', 800, 755, true),
(863, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'EV', 'Distilled Water', 20, 1168, true),
(864, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'EV', 'Shampoo', 120, 1168, true),
(865, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'EV', 'Coolant Top Up', 212, 1168, true),
(866, 'GLOBAL', 'Mini Paid Service', 'Curvv', 'EV', 'Sunroof Greece', 800, 1168, true),
(867, 'GLOBAL', 'Mini Paid Service', 'Harrier', 'Diesel', 'Distilled Water', 20, 1250, true),
(868, 'GLOBAL', 'Mini Paid Service', 'Harrier', 'Diesel', 'Shampoo', 120, 1250, true),
(869, 'GLOBAL', 'Mini Paid Service', 'Harrier', 'Diesel', 'Coolant Top Up', 100, 1250, true),
(870, 'GLOBAL', 'Mini Paid Service', 'Harrier', 'Diesel', 'Oil Filter Change', 792, 1250, true),
(871, 'GLOBAL', 'Mini Paid Service', 'Harrier', 'Diesel', 'Sunroof Greece', 800, 1250, true),
(872, 'GLOBAL', 'Mini Paid Service', 'Safari', 'Diesel', 'Distilled Water', 20, 1250, true),
(873, 'GLOBAL', 'Mini Paid Service', 'Safari', 'Diesel', 'Shampoo', 120, 1250, true),
(874, 'GLOBAL', 'Mini Paid Service', 'Safari', 'Diesel', 'Coolant Top Up', 100, 1250, true),
(875, 'GLOBAL', 'Mini Paid Service', 'Safari', 'Diesel', 'Oil Filter Change', 792, 1250, true),
(876, 'GLOBAL', 'Mini Paid Service', 'Safari', 'Diesel', 'Sunroof Greece', 800, 1250, true),
(877, 'GLOBAL', 'Mini Paid Service', 'Safari', 'Diesel', 'oil Top up', 650, 1250, true)
