-- ACCOUNTS-001 / DBL-0045
-- Accounts desk: module `accounts`, mechanical invoice capture, bodyshop customer-diff book.
-- Run this file in the Supabase SQL Editor (safe to re-run).
-- Do not re-run DBL-0026 / 0031–0037 / 0042 / 0043 / 0044.
-- Timestamp 20260911130000 because 20260911120000 is DBL-0044 (busy_parts).
-- Authority: supabase/backups/full_metadata.sql

-- ---------------------------------------------------------------------------
-- A. Module
-- ---------------------------------------------------------------------------
INSERT INTO public.modules (name, label, description, route, sort_order, is_active)
VALUES (
  'accounts',
  'Accounts',
  'Mechanical Mark Done invoice capture and Bodyshop Stage 18 customer-diff book. Not BUSY export. Not Recovery insurance due.',
  '/accounts',
  30,
  true
)
ON CONFLICT (name) DO UPDATE SET
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  route = EXCLUDED.route,
  sort_order = EXCLUDED.sort_order,
  is_active = true;

-- ---------------------------------------------------------------------------
-- B. Mechanical invoice table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.accounts_mechanical_invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reception_entry_id bigint NOT NULL REFERENCES public.service_reception_entries(id) ON DELETE CASCADE,
  jc_number text NOT NULL,
  invoice_number text,
  invoice_date date,
  billed_amount numeric(14,2),
  payment_status text NOT NULL DEFAULT 'pending',
  amount_received numeric(14,2),
  payment_notes text,
  captured_by text,
  captured_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT accounts_mechanical_invoices_reception_uid UNIQUE (reception_entry_id),
  CONSTRAINT accounts_mechanical_invoices_jc_not_blank CHECK (length(btrim(jc_number)) > 0),
  CONSTRAINT accounts_mechanical_invoices_pay_check CHECK (
    payment_status = ANY (ARRAY['pending'::text, 'partial'::text, 'received'::text, 'not_received'::text])
  ),
  CONSTRAINT accounts_mechanical_invoices_billed_check CHECK (
    billed_amount IS NULL OR billed_amount >= 0
  ),
  CONSTRAINT accounts_mechanical_invoices_received_check CHECK (
    amount_received IS NULL OR amount_received >= 0
  )
);

CREATE INDEX IF NOT EXISTS idx_accounts_mech_inv_jc
  ON public.accounts_mechanical_invoices (jc_number);
CREATE INDEX IF NOT EXISTS idx_accounts_mech_inv_status
  ON public.accounts_mechanical_invoices (payment_status);
CREATE INDEX IF NOT EXISTS idx_accounts_mech_inv_date
  ON public.accounts_mechanical_invoices (invoice_date);

COMMENT ON TABLE public.accounts_mechanical_invoices IS
  'ACCOUNTS-001: Accounts-captured mechanical invoice/payment after Service Advisor Mark Done.';

ALTER TABLE public.accounts_mechanical_invoices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS accounts_mechanical_invoices_select_accounts ON public.accounts_mechanical_invoices;
CREATE POLICY accounts_mechanical_invoices_select_accounts
  ON public.accounts_mechanical_invoices
  FOR SELECT
  TO authenticated
  USING (
    public.is_admin()
    OR public.has_module_view('accounts')
    OR public.has_module_modify('accounts')
  );

-- Writes only via SECURITY DEFINER RPC.
REVOKE INSERT, UPDATE, DELETE ON public.accounts_mechanical_invoices FROM authenticated, anon;
GRANT SELECT ON public.accounts_mechanical_invoices TO authenticated;
GRANT ALL ON public.accounts_mechanical_invoices TO service_role;

-- ---------------------------------------------------------------------------
-- C. Permission helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.accounts_can_access()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  RETURN public.is_admin()
    OR public.has_module_view('accounts')
    OR public.has_module_modify('accounts');
END;
$$;

CREATE OR REPLACE FUNCTION public.bodyshop_settlement_can_post_customer(p_repair_card_id integer)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  IF public.is_admin() THEN
    RETURN true;
  END IF;
  IF public.has_module_view('accounts')
     OR public.has_module_modify('accounts') THEN
    RETURN true;
  END IF;
  RETURN public.bodyshop_settlement_can_modify(p_repair_card_id);
END;
$$;

-- Accounts users must load settlement for Stage 18 customer posting (org-wide).
CREATE OR REPLACE FUNCTION public.bodyshop_settlement_can_view(p_repair_card_id integer)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_dealer text;
BEGIN
  IF public.is_admin() THEN
    RETURN true;
  END IF;

  IF public.has_module_view('accounts')
     OR public.has_module_modify('accounts') THEN
    RETURN true;
  END IF;

  -- Recovery is org-wide. Do not require a mapped dealer or branch.
  IF public.has_module_view('bodyshop_recovery')
     OR public.has_module_modify('bodyshop_recovery') THEN
    RETURN true;
  END IF;

  IF NOT (
    public.has_module_view('bodyshop_repair')
    OR public.has_module_modify('bodyshop_repair')
    OR public.has_module_view('bodyshop_tracker')
    OR public.has_module_view('bodyshop_floor')
  ) THEN
    RETURN false;
  END IF;

  SELECT sre.dealer_code
    INTO v_dealer
    FROM public.bodyshop_repair_cards brc
    LEFT JOIN public.service_reception_entries sre ON sre.id = brc.reception_entry_id
   WHERE brc.id = p_repair_card_id;

  IF v_dealer IS NULL THEN
    RETURN false;
  END IF;
  RETURN public.dealer_code_in_scope(v_dealer);
END;
$$;

-- ---------------------------------------------------------------------------
-- D. Mechanical list + upsert
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.list_accounts_mechanical_cases()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_rows jsonb;
BEGIN
  IF NOT public.accounts_can_access() THEN
    RAISE EXCEPTION 'permission denied: requires accounts view'
      USING ERRCODE = '42501';
  END IF;

  SELECT COALESCE(
    jsonb_agg(to_jsonb(x) ORDER BY x.invoice_done_at DESC NULLS LAST, x.reception_entry_id DESC),
    '[]'::jsonb
  )
    INTO v_rows
    FROM (
      SELECT
        e.id AS reception_entry_id,
        e.jc_number,
        e.reg_number,
        e.model,
        e.service_type,
        e.sa_name,
        e.sa_display_name,
        e.sa_employee_code,
        e.branch,
        e.owner_name,
        e.owner_phone,
        e.invoice_done_at,
        e.invoice_done_by,
        e.created_at,
        inv.invoice_number,
        inv.invoice_date,
        inv.billed_amount,
        inv.payment_status,
        inv.amount_received,
        inv.payment_notes,
        inv.captured_by,
        inv.captured_at,
        inv.updated_at AS invoice_updated_at
      FROM public.service_reception_entries e
      LEFT JOIN public.accounts_mechanical_invoices inv
        ON inv.reception_entry_id = e.id
      WHERE e.invoice_done_at IS NOT NULL
        AND NULLIF(btrim(e.jc_number), '') IS NOT NULL
        AND public.is_floor_incharge_service_type(e.service_type)
    ) x;

  RETURN v_rows;
END;
$$;

CREATE OR REPLACE FUNCTION public.upsert_accounts_mechanical_invoice(
  p_reception_entry_id bigint,
  p_invoice_number text DEFAULT NULL,
  p_invoice_date date DEFAULT NULL,
  p_billed_amount numeric DEFAULT NULL,
  p_payment_status text DEFAULT NULL,
  p_amount_received numeric DEFAULT NULL,
  p_payment_notes text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_entry public.service_reception_entries%ROWTYPE;
  v_actor text;
  v_status text;
  v_row public.accounts_mechanical_invoices%ROWTYPE;
BEGIN
  IF NOT public.accounts_can_access() THEN
    RAISE EXCEPTION 'permission denied: requires accounts view'
      USING ERRCODE = '42501';
  END IF;

  SELECT * INTO v_entry
    FROM public.service_reception_entries
   WHERE id = p_reception_entry_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'reception entry % not found', p_reception_entry_id
      USING ERRCODE = 'P0002';
  END IF;
  IF v_entry.invoice_done_at IS NULL THEN
    RAISE EXCEPTION 'case is not Mark Done on Service Advisor'
      USING ERRCODE = '23514';
  END IF;
  IF NOT public.is_floor_incharge_service_type(v_entry.service_type) THEN
    RAISE EXCEPTION 'not a mechanical Floor Incharge service type'
      USING ERRCODE = '23514';
  END IF;
  IF NULLIF(btrim(v_entry.jc_number), '') IS NULL THEN
    RAISE EXCEPTION 'jc_number is required'
      USING ERRCODE = '23514';
  END IF;

  v_status := lower(btrim(COALESCE(p_payment_status, 'pending')));
  IF v_status NOT IN ('pending', 'partial', 'received', 'not_received') THEN
    RAISE EXCEPTION 'invalid payment_status'
      USING ERRCODE = '23514';
  END IF;
  IF p_billed_amount IS NOT NULL AND p_billed_amount < 0 THEN
    RAISE EXCEPTION 'billed_amount cannot be negative'
      USING ERRCODE = '23514';
  END IF;
  IF p_amount_received IS NOT NULL AND p_amount_received < 0 THEN
    RAISE EXCEPTION 'amount_received cannot be negative'
      USING ERRCODE = '23514';
  END IF;

  v_actor := COALESCE(
    NULLIF(auth.jwt() ->> 'email', ''),
    NULLIF(auth.uid()::text, ''),
    'system'
  );

  INSERT INTO public.accounts_mechanical_invoices (
    reception_entry_id, jc_number, invoice_number, invoice_date, billed_amount,
    payment_status, amount_received, payment_notes, captured_by, captured_at, updated_at
  ) VALUES (
    p_reception_entry_id,
    btrim(v_entry.jc_number),
    NULLIF(btrim(p_invoice_number), ''),
    p_invoice_date,
    CASE WHEN p_billed_amount IS NULL THEN NULL ELSE round(p_billed_amount, 2) END,
    v_status,
    CASE WHEN p_amount_received IS NULL THEN NULL ELSE round(p_amount_received, 2) END,
    NULLIF(btrim(p_payment_notes), ''),
    v_actor,
    now(),
    now()
  )
  ON CONFLICT (reception_entry_id) DO UPDATE SET
    jc_number = EXCLUDED.jc_number,
    invoice_number = EXCLUDED.invoice_number,
    invoice_date = EXCLUDED.invoice_date,
    billed_amount = EXCLUDED.billed_amount,
    payment_status = EXCLUDED.payment_status,
    amount_received = EXCLUDED.amount_received,
    payment_notes = EXCLUDED.payment_notes,
    updated_at = now();

  SELECT * INTO v_row
    FROM public.accounts_mechanical_invoices
   WHERE reception_entry_id = p_reception_entry_id;

  RETURN to_jsonb(v_row);
END;
$$;

-- ---------------------------------------------------------------------------
-- E. Bodyshop customer-diff book
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.list_accounts_bodyshop_cases()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_rows jsonb;
BEGIN
  IF NOT public.accounts_can_access() THEN
    RAISE EXCEPTION 'permission denied: requires accounts view'
      USING ERRCODE = '42501';
  END IF;

  SELECT COALESCE(
    jsonb_agg(to_jsonb(x) ORDER BY x.invoice_date DESC NULLS LAST, x.repair_card_id DESC),
    '[]'::jsonb
  )
    INTO v_rows
    FROM (
      SELECT
        s.repair_card_id,
        s.job_card_no,
        c.reg_number,
        c.customer_name,
        c.branch,
        c.sa_name,
        c.insurance_company,
        c.insurance_policy_no,
        c.overall_status,
        c.current_stage,
        s.invoice_number,
        s.invoice_date,
        s.invoice_amount,
        c.billed_amount,
        s.invoice_account,
        s.customer_diff_amount,
        s.customer_settlement_kind,
        s.customer_posted_amount,
        s.customer_remaining_amount,
        s.customer_payment_status,
        s.do_amount,
        s.insurance_due_amount,
        s.do_payment_status
      FROM public.bodyshop_settlements s
      JOIN public.bodyshop_repair_cards c ON c.id = s.repair_card_id
      WHERE NULLIF(btrim(s.invoice_number), '') IS NOT NULL
        AND COALESCE(s.invoice_amount, c.billed_amount) IS NOT NULL
        AND COALESCE(c.overall_status, 'active') <> 'cancelled'
    ) x;

  RETURN v_rows;
END;
$$;

-- ---------------------------------------------------------------------------
-- F. Customer path on add / reverse — keep DO path unchanged
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.add_bodyshop_settlement_line(
  p_repair_card_id integer,
  p_party text DEFAULT NULL,
  p_line_type text DEFAULT NULL,
  p_component text DEFAULT NULL,
  p_amount numeric DEFAULT NULL,
  p_txn_date date DEFAULT NULL,
  p_reference text DEFAULT NULL,
  p_remarks text DEFAULT NULL,
  p_main_amount numeric DEFAULT NULL,
  p_gst_amount numeric DEFAULT NULL,
  p_tds_amount numeric DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_id bigint;
  v_h public.bodyshop_settlements%ROWTYPE;
  v_actor_id uuid;
  v_actor_email text;
  v_date date;
  v_new_release numeric;
  v_main numeric;
  v_gst numeric;
  v_tds numeric;
BEGIN
  v_main := CASE WHEN COALESCE(p_main_amount, 0) > 0 THEN round(p_main_amount, 2) ELSE 0 END;
  v_gst := CASE WHEN COALESCE(p_gst_amount, 0) > 0 THEN round(p_gst_amount, 2) ELSE 0 END;
  v_tds := CASE WHEN COALESCE(p_tds_amount, 0) > 0 THEN round(p_tds_amount, 2) ELSE 0 END;

  IF v_main > 0 OR v_gst > 0 OR v_tds > 0 THEN
    IF NOT public.bodyshop_settlement_can_post_do(p_repair_card_id) THEN
      RAISE EXCEPTION 'permission denied: requires bodyshop_recovery view or bodyshop_repair modify'
        USING ERRCODE = '42501';
    END IF;

    v_id := public._bodyshop_ensure_settlement(p_repair_card_id);
    SELECT * INTO v_h FROM public.bodyshop_settlements WHERE id = v_id;
    SELECT a.actor_id, a.actor_email INTO v_actor_id, v_actor_email
      FROM public._bodyshop_settlement_actor() a;
    v_date := COALESCE(p_txn_date, CURRENT_DATE);

    IF v_h.do_amount IS NULL THEN
      RAISE EXCEPTION 'DO amount must be captured before posting DO payment'
        USING ERRCODE = '23514';
    END IF;
    v_new_release := round(COALESCE(v_h.do_released_amount, 0), 2) + v_main + v_gst + v_tds;
    IF v_new_release > round(v_h.do_amount, 2) THEN
      RAISE EXCEPTION 'Main + GST + TDS cannot exceed DO amount'
        USING ERRCODE = '23514';
    END IF;

    IF v_main > 0 THEN
      INSERT INTO public.bodyshop_settlement_lines (
        settlement_id, repair_card_id, party, line_type, component, amount,
        txn_date, reference, remarks, actor_id, actor_email
      ) VALUES (
        v_id, p_repair_card_id, 'insurance', 'do_component', 'MAIN', v_main,
        v_date, p_reference, p_remarks, v_actor_id, v_actor_email
      );
    END IF;
    IF v_gst > 0 THEN
      INSERT INTO public.bodyshop_settlement_lines (
        settlement_id, repair_card_id, party, line_type, component, amount,
        txn_date, reference, remarks, actor_id, actor_email
      ) VALUES (
        v_id, p_repair_card_id, 'insurance', 'do_component', 'GST', v_gst,
        v_date, p_reference, p_remarks, v_actor_id, v_actor_email
      );
    END IF;
    IF v_tds > 0 THEN
      INSERT INTO public.bodyshop_settlement_lines (
        settlement_id, repair_card_id, party, line_type, component, amount,
        txn_date, reference, remarks, actor_id, actor_email
      ) VALUES (
        v_id, p_repair_card_id, 'insurance', 'do_component', 'TDS', v_tds,
        v_date, p_reference, p_remarks, v_actor_id, v_actor_email
      );
    END IF;
    UPDATE public.bodyshop_settlements SET do_not_received = false, updated_by = v_actor_email WHERE id = v_id;
    PERFORM public.recalc_bodyshop_settlement(v_id);
    RETURN public.get_bodyshop_settlement(p_repair_card_id);
  END IF;

  IF NOT public.bodyshop_settlement_can_post_customer(p_repair_card_id) THEN
    RAISE EXCEPTION 'permission denied: requires accounts view or bodyshop_repair modify'
      USING ERRCODE = '42501';
  END IF;

  v_id := public._bodyshop_ensure_settlement(p_repair_card_id);
  SELECT * INTO v_h FROM public.bodyshop_settlements WHERE id = v_id;
  SELECT a.actor_id, a.actor_email INTO v_actor_id, v_actor_email
    FROM public._bodyshop_settlement_actor() a;
  v_date := COALESCE(p_txn_date, CURRENT_DATE);

  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'amount must be greater than 0' USING ERRCODE = '23514';
  END IF;

  IF upper(btrim(COALESCE(p_component, ''))) IN ('CUSTOMER', 'CUSTOMER_REFUND')
     OR lower(btrim(COALESCE(p_party, ''))) = 'customer' THEN
    PERFORM public.recalc_bodyshop_settlement(v_id);
    SELECT * INTO v_h FROM public.bodyshop_settlements WHERE id = v_id;
    IF v_h.customer_settlement_kind IS NULL OR v_h.customer_settlement_kind = 'none' THEN
      RAISE EXCEPTION 'no customer due or refund to post against'
        USING ERRCODE = '23514';
    END IF;
    IF v_h.customer_settlement_kind = 'due' THEN
      IF upper(btrim(COALESCE(p_component, 'CUSTOMER'))) = 'CUSTOMER_REFUND'
         OR lower(btrim(COALESCE(p_line_type, 'receipt'))) = 'refund' THEN
        RAISE EXCEPTION 'refunds are not allowed when customer diff is recoverable'
          USING ERRCODE = '23514';
      END IF;
      IF round(p_amount, 2) > round(COALESCE(v_h.customer_remaining_amount, 0), 2) THEN
        RAISE EXCEPTION 'customer receipt cannot exceed remaining recoverable'
          USING ERRCODE = '23514';
      END IF;
      INSERT INTO public.bodyshop_settlement_lines (
        settlement_id, repair_card_id, party, line_type, component, amount,
        txn_date, reference, remarks, actor_id, actor_email
      ) VALUES (
        v_id, p_repair_card_id, 'customer', 'receipt', 'CUSTOMER', round(p_amount, 2),
        v_date, p_reference, p_remarks, v_actor_id, v_actor_email
      );
    ELSE
      IF upper(btrim(COALESCE(p_component, 'CUSTOMER_REFUND'))) = 'CUSTOMER'
         OR lower(btrim(COALESCE(p_line_type, 'refund'))) = 'receipt' THEN
        RAISE EXCEPTION 'receipts are not allowed when customer diff is a refund'
          USING ERRCODE = '23514';
      END IF;
      IF round(p_amount, 2) > round(COALESCE(v_h.customer_remaining_amount, 0), 2) THEN
        RAISE EXCEPTION 'customer refund cannot exceed remaining refund'
          USING ERRCODE = '23514';
      END IF;
      INSERT INTO public.bodyshop_settlement_lines (
        settlement_id, repair_card_id, party, line_type, component, amount,
        txn_date, reference, remarks, actor_id, actor_email
      ) VALUES (
        v_id, p_repair_card_id, 'customer', 'refund', 'CUSTOMER_REFUND', round(p_amount, 2),
        v_date, p_reference, p_remarks, v_actor_id, v_actor_email
      );
    END IF;
    UPDATE public.bodyshop_settlements SET customer_not_received = false, updated_by = v_actor_email WHERE id = v_id;
    PERFORM public.recalc_bodyshop_settlement(v_id);
    RETURN public.get_bodyshop_settlement(p_repair_card_id);
  END IF;

  RAISE EXCEPTION 'unsupported settlement line; use Main/GST/TDS batch or customer amount'
    USING ERRCODE = '23514';
END;
$$;

CREATE OR REPLACE FUNCTION public.reverse_bodyshop_settlement_line(p_line_id bigint, p_reason text DEFAULT NULL::text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_line public.bodyshop_settlement_lines%ROWTYPE;
  v_actor_id uuid;
  v_actor_email text;
  v_allowed boolean;
BEGIN
  SELECT * INTO v_line FROM public.bodyshop_settlement_lines WHERE id = p_line_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'line % not found', p_line_id USING ERRCODE = 'P0002';
  END IF;

  IF v_line.party = 'insurance' AND v_line.line_type = 'do_component' THEN
    v_allowed := public.bodyshop_settlement_can_post_do(v_line.repair_card_id);
  ELSIF v_line.party = 'customer' THEN
    v_allowed := public.bodyshop_settlement_can_post_customer(v_line.repair_card_id);
  ELSE
    v_allowed := public.bodyshop_settlement_can_modify(v_line.repair_card_id);
  END IF;
  IF NOT v_allowed THEN
    RAISE EXCEPTION 'permission denied'
      USING ERRCODE = '42501';
  END IF;

  IF v_line.is_reversed OR v_line.line_type = 'reversal' THEN
    RAISE EXCEPTION 'line is already reversed' USING ERRCODE = '23514';
  END IF;

  SELECT a.actor_id, a.actor_email INTO v_actor_id, v_actor_email
    FROM public._bodyshop_settlement_actor() a;

  INSERT INTO public.bodyshop_settlement_lines (
    settlement_id, repair_card_id, party, line_type, component, amount,
    txn_date, reference, remarks, reverses_line_id, actor_id, actor_email
  ) VALUES (
    v_line.settlement_id, v_line.repair_card_id, v_line.party, 'reversal', v_line.component, v_line.amount,
    CURRENT_DATE, v_line.reference, COALESCE(p_reason, 'reversed'), p_line_id, v_actor_id, v_actor_email
  );

  PERFORM public._bodyshop_settlement_mark_line_reversed(p_line_id);
  PERFORM public.recalc_bodyshop_settlement(v_line.settlement_id);
  RETURN public.get_bodyshop_settlement(v_line.repair_card_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.accounts_can_access() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.bodyshop_settlement_can_post_customer(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.bodyshop_settlement_can_view(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.list_accounts_mechanical_cases() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.upsert_accounts_mechanical_invoice(bigint, text, date, numeric, text, numeric, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.list_accounts_bodyshop_cases() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.add_bodyshop_settlement_line(integer, text, text, text, numeric, date, text, text, numeric, numeric, numeric) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reverse_bodyshop_settlement_line(bigint, text) TO authenticated, service_role;
