-- BODYSHOP-002: Intake vehicle photo metadata + backend enforcement (authoritative additive migration)
-- Source of truth aligned to: local_folder/backups/full_database.sql

begin;

create table if not exists public.bodyshop_intake_vehicle_photos (
  id bigint primary key generated always as identity,
  dealer_code text not null default public.my_dealer_code(),
  reception_entry_id bigint not null references public.service_reception_entries(id) on delete cascade,
  job_card_no text not null,
  reg_number text not null,
  customer_type text not null,
  storage_bucket text not null default 'autodoc',
  storage_path text not null,
  drive_url text,
  drive_file_id text,
  file_name text,
  content_type text,
  file_size_bytes bigint,
  uploaded_by text not null default coalesce(auth.jwt() ->> 'email', auth.uid()::text, 'system'),
  uploaded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bodyshop_intake_vehicle_photos_customer_type_check
    check (customer_type = any (array['individual'::text, 'firm'::text, 'foc'::text, 'cash'::text])),
  constraint bodyshop_intake_vehicle_photos_job_card_no_not_blank
    check (length(btrim(job_card_no)) > 0),
  constraint bodyshop_intake_vehicle_photos_reg_number_not_blank
    check (length(btrim(reg_number)) > 0),
  constraint bodyshop_intake_vehicle_photos_storage_path_not_blank
    check (length(btrim(storage_path)) > 0),
  constraint bodyshop_intake_vehicle_photos_content_type_image_check
    check (content_type is null or content_type like 'image/%'),
  constraint bodyshop_intake_vehicle_photos_file_size_non_negative_check
    check (file_size_bytes is null or file_size_bytes >= 0),
  constraint bodyshop_intake_vehicle_photos_unique_storage_path unique (storage_path)
);

create index if not exists idx_bodyshop_intake_vehicle_photos_reception_entry
  on public.bodyshop_intake_vehicle_photos (reception_entry_id);

create index if not exists idx_bodyshop_intake_vehicle_photos_job_card
  on public.bodyshop_intake_vehicle_photos (job_card_no);

create index if not exists idx_bodyshop_intake_vehicle_photos_dealer
  on public.bodyshop_intake_vehicle_photos (dealer_code);

create index if not exists idx_bodyshop_intake_vehicle_photos_uploaded_at
  on public.bodyshop_intake_vehicle_photos (uploaded_at desc);

comment on table public.bodyshop_intake_vehicle_photos is
  'Bodyshop intake vehicle photo metadata captured from Service Advisor Accident flow. Max 20 photos enforced per reception_entry_id.';

comment on column public.bodyshop_intake_vehicle_photos.reception_entry_id is
  'FK to service_reception_entries.id for Accident intake row linkage.';

comment on column public.bodyshop_intake_vehicle_photos.storage_path is
  'Supabase storage object path in autodoc bucket for uploaded intake image.';

comment on column public.bodyshop_intake_vehicle_photos.drive_url is
  'Universal Drive URL generated by edge function after offload.';

comment on column public.bodyshop_intake_vehicle_photos.drive_file_id is
  'Universal Drive file id returned by edge function.';

create or replace function public.enforce_bodyshop_intake_photo_limit()
returns trigger
language plpgsql
as $$
declare
  existing_count integer;
begin
  select count(*)
    into existing_count
  from public.bodyshop_intake_vehicle_photos p
  where p.reception_entry_id = new.reception_entry_id
    and (tg_op = 'INSERT' or p.id <> new.id);

  if existing_count >= 20 then
    raise exception 'Maximum 20 bodyshop intake photos allowed per reception entry.'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_bodyshop_intake_vehicle_photos_limit
  on public.bodyshop_intake_vehicle_photos;

create trigger trg_bodyshop_intake_vehicle_photos_limit
  before insert or update on public.bodyshop_intake_vehicle_photos
  for each row execute function public.enforce_bodyshop_intake_photo_limit();

drop trigger if exists trg_bodyshop_intake_vehicle_photos_updated_at
  on public.bodyshop_intake_vehicle_photos;

create trigger trg_bodyshop_intake_vehicle_photos_updated_at
  before update on public.bodyshop_intake_vehicle_photos
  for each row execute function public.set_updated_at();

alter table public.bodyshop_intake_vehicle_photos enable row level security;

drop policy if exists admin_unrestricted_all_ops_v1 on public.bodyshop_intake_vehicle_photos;
create policy admin_unrestricted_all_ops_v1
  on public.bodyshop_intake_vehicle_photos
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists bodyshop_intake_vehicle_photos_select_rbac_v1 on public.bodyshop_intake_vehicle_photos;
create policy bodyshop_intake_vehicle_photos_select_rbac_v1
  on public.bodyshop_intake_vehicle_photos
  for select
  to authenticated
  using (
    public.is_admin()
    or (
      (
        public.has_module_view('service_advisor')
        or public.has_module_view('reception')
        or public.has_module_view('bodyshop_floor')
        or public.has_module_view('bodyshop_repair')
        or public.has_module_view('bodyshop_tracker')
      )
      and public.dealer_code_in_scope(dealer_code)
    )
  );

drop policy if exists bodyshop_intake_vehicle_photos_insert_rbac_v1 on public.bodyshop_intake_vehicle_photos;
create policy bodyshop_intake_vehicle_photos_insert_rbac_v1
  on public.bodyshop_intake_vehicle_photos
  for insert
  to authenticated
  with check (
    public.is_admin()
    or (
      (
        public.has_module_modify('service_advisor')
        or public.has_module_modify('reception')
        or public.has_module_modify('bodyshop_repair')
      )
      and public.dealer_code_in_scope(dealer_code)
    )
  );

drop policy if exists bodyshop_intake_vehicle_photos_update_rbac_v1 on public.bodyshop_intake_vehicle_photos;
create policy bodyshop_intake_vehicle_photos_update_rbac_v1
  on public.bodyshop_intake_vehicle_photos
  for update
  to authenticated
  using (
    public.is_admin()
    or (
      (
        public.has_module_modify('service_advisor')
        or public.has_module_modify('reception')
        or public.has_module_modify('bodyshop_repair')
      )
      and public.dealer_code_in_scope(dealer_code)
    )
  )
  with check (
    public.is_admin()
    or (
      (
        public.has_module_modify('service_advisor')
        or public.has_module_modify('reception')
        or public.has_module_modify('bodyshop_repair')
      )
      and public.dealer_code_in_scope(dealer_code)
    )
  );

drop policy if exists bodyshop_intake_vehicle_photos_delete_rbac_v1 on public.bodyshop_intake_vehicle_photos;
create policy bodyshop_intake_vehicle_photos_delete_rbac_v1
  on public.bodyshop_intake_vehicle_photos
  for delete
  to authenticated
  using (
    public.is_admin()
    or (
      (
        public.has_module_delete('service_advisor')
        or public.has_module_delete('reception')
        or public.has_module_delete('bodyshop_repair')
      )
      and public.dealer_code_in_scope(dealer_code)
    )
  );

grant all on table public.bodyshop_intake_vehicle_photos to authenticated;
grant all on table public.bodyshop_intake_vehicle_photos to service_role;
grant all on sequence public.bodyshop_intake_vehicle_photos_id_seq to authenticated;
grant all on sequence public.bodyshop_intake_vehicle_photos_id_seq to service_role;

grant execute on function public.enforce_bodyshop_intake_photo_limit() to authenticated;
grant execute on function public.enforce_bodyshop_intake_photo_limit() to service_role;

commit;
