-- ACCOUNTS-001 / DBL-0046
-- Mechanical invoice stays 1:1. Customer receipts become append-only lines.
-- Payment status is derived from billed vs sum(lines). Invoice file stays on
-- service_reception_entries (the unused Service Advisor upload columns).
-- Run this file in the Supabase SQL Editor (safe to re-run).
-- Do not re-run DBL-0026 / 0031–0037 / 0042 / 0043 / 0044 / 0045.
-- Timestamp 20260911140000.
-- Authority: supabase/backups/full_metadata.sql + DBL-0045 applied objects.

-- ---------------------------------------------------------------------------
-- A. Payment lines
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.accounts_mechanical_payment_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reception_entry_id bigint NOT NULL REFERENCES public.service_reception_entries(id) ON DELETE CASCADE,
  mechanical_invoice_id bigint NOT NULL REFERENCES public.accounts_mechanical_invoices(id) ON DELETE CASCADE,
  amount numeric(14,2) NOT NULL,
  payment_mode text NOT NULL,
  reference text,
  posted_by text,
  posted_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT accounts_mechanical_payment_lines_amount_check CHECK (amount > 0),
  CONSTRAINT accounts_mechanical_payment_lines_mode_check CHECK (
    payment_mode = ANY (ARRAY['cash'::text, 'upi'::text, 'card'::text, 'cheque'::text, 'bank'::text, 'other'::text])
  )
);

CREATE INDEX IF NOT EXISTS idx_accounts_mech_pay_reception
  ON public.accounts_mechanical_payment_lines (reception_entry_id, posted_at);

CREATE INDEX IF NOT EXISTS idx_accounts_mech_pay_invoice
  ON public.accounts_mechanical_payment_lines (mechanical_invoice_id);

COMMENT ON TABLE public.accounts_mechanical_payment_lines IS
  'ACCOUNTS-001 / DBL-0046: Append-only mechanical receipts until billed remaining is 0.';

ALTER TABLE public.accounts_mechanical_payment_lines ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS accounts_mechanical_payment_lines_select_accounts ON public.accounts_mechanical_payment_lines;
CREATE POLICY accounts_mechanical_payment_lines_select_accounts
  ON public.accounts_mechanical_payment_lines
  FOR SELECT
  TO authenticated
  USING (
    public.is_admin()
    OR public.has_module_view('accounts')
    OR public.has_module_modify('accounts')
  );

REVOKE INSERT, UPDATE, DELETE ON public.accounts_mechanical_payment_lines FROM authenticated, anon;
GRANT SELECT ON public.accounts_mechanical_payment_lines TO authenticated;
GRANT ALL ON public.accounts_mechanical_payment_lines TO service_role;

-- ---------------------------------------------------------------------------
-- B. Backfill header totals into one line each
-- ---------------------------------------------------------------------------
INSERT INTO public.accounts_mechanical_payment_lines (
  reception_entry_id, mechanical_invoice_id, amount, payment_mode, reference, posted_by, posted_at
)
SELECT
  inv.reception_entry_id,
  inv.id,
  round(inv.amount_received, 2),
  'other',
  NULLIF(btrim(inv.payment_notes), ''),
  inv.captured_by,
  COALESCE(inv.captured_at, inv.updated_at, now())
FROM public.accounts_mechanical_invoices inv
WHERE inv.amount_received IS NOT NULL
  AND inv.amount_received > 0
  AND NOT EXISTS (
    SELECT 1
    FROM public.accounts_mechanical_payment_lines l
    WHERE l.mechanical_invoice_id = inv.id
  );

-- ---------------------------------------------------------------------------
-- C. Recalc header from lines
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.accounts_mechanical_recalc(p_reception_entry_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_billed numeric;
  v_received numeric;
  v_status text;
BEGIN
  SELECT billed_amount INTO v_billed
    FROM public.accounts_mechanical_invoices
   WHERE reception_entry_id = p_reception_entry_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT COALESCE(sum(l.amount), 0) INTO v_received
    FROM public.accounts_mechanical_payment_lines l
   WHERE l.reception_entry_id = p_reception_entry_id;

  IF v_billed IS NULL THEN
    v_status := 'pending';
  ELSIF v_billed = 0 THEN
    v_status := 'received';
  ELSIF v_received <= 0 THEN
    v_status := 'pending';
  ELSIF v_received < v_billed THEN
    v_status := 'partial';
  ELSE
    v_status := 'received';
  END IF;

  UPDATE public.accounts_mechanical_invoices
     SET amount_received = CASE WHEN v_received = 0 THEN NULL ELSE round(v_received, 2) END,
         payment_status = v_status,
         updated_at = now()
   WHERE reception_entry_id = p_reception_entry_id;
END;
$$;

DO $$
DECLARE
  r record;
BEGIN
  FOR r IN SELECT reception_entry_id FROM public.accounts_mechanical_invoices
  LOOP
    PERFORM public.accounts_mechanical_recalc(r.reception_entry_id);
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION public.accounts_mechanical_case_json(p_reception_entry_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_row jsonb;
BEGIN
  SELECT to_jsonb(x) INTO v_row
    FROM (
      SELECT
        e.id AS reception_entry_id,
        e.jc_number,
        e.reg_number,
        e.model,
        e.service_type,
        e.sa_name,
        e.sa_display_name,
        e.sa_employee_code,
        e.branch,
        e.owner_name,
        e.owner_phone,
        e.invoice_done_at,
        e.invoice_done_by,
        e.created_at,
        e.invoice_storage_path,
        e.invoice_file_name,
        e.invoice_drive_url,
        inv.invoice_number,
        inv.invoice_date,
        inv.billed_amount,
        inv.payment_status,
        inv.amount_received,
        CASE
          WHEN inv.billed_amount IS NULL THEN NULL
          ELSE GREATEST(0, round(inv.billed_amount - COALESCE(inv.amount_received, 0), 2))
        END AS remaining_amount,
        inv.payment_notes,
        inv.captured_by,
        inv.captured_at,
        inv.updated_at AS invoice_updated_at
      FROM public.service_reception_entries e
      LEFT JOIN public.accounts_mechanical_invoices inv
        ON inv.reception_entry_id = e.id
      WHERE e.id = p_reception_entry_id
    ) x;
  RETURN v_row;
END;
$$;

-- ---------------------------------------------------------------------------
-- D. Replace list + header upsert
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.list_accounts_mechanical_cases()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_rows jsonb;
BEGIN
  IF NOT public.accounts_can_access() THEN
    RAISE EXCEPTION 'permission denied: requires accounts view'
      USING ERRCODE = '42501';
  END IF;

  SELECT COALESCE(
    jsonb_agg(to_jsonb(x) ORDER BY x.invoice_done_at DESC NULLS LAST, x.reception_entry_id DESC),
    '[]'::jsonb
  )
    INTO v_rows
    FROM (
      SELECT
        e.id AS reception_entry_id,
        e.jc_number,
        e.reg_number,
        e.model,
        e.service_type,
        e.sa_name,
        e.sa_display_name,
        e.sa_employee_code,
        e.branch,
        e.owner_name,
        e.owner_phone,
        e.invoice_done_at,
        e.invoice_done_by,
        e.created_at,
        e.invoice_storage_path,
        e.invoice_file_name,
        e.invoice_drive_url,
        inv.invoice_number,
        inv.invoice_date,
        inv.billed_amount,
        inv.payment_status,
        inv.amount_received,
        CASE
          WHEN inv.billed_amount IS NULL THEN NULL
          ELSE GREATEST(0, round(inv.billed_amount - COALESCE(inv.amount_received, 0), 2))
        END AS remaining_amount,
        inv.payment_notes,
        inv.captured_by,
        inv.captured_at,
        inv.updated_at AS invoice_updated_at
      FROM public.service_reception_entries e
      LEFT JOIN public.accounts_mechanical_invoices inv
        ON inv.reception_entry_id = e.id
      WHERE e.invoice_done_at IS NOT NULL
        AND NULLIF(btrim(e.jc_number), '') IS NOT NULL
        AND public.is_floor_incharge_service_type(e.service_type)
    ) x;

  RETURN v_rows;
END;
$$;

CREATE OR REPLACE FUNCTION public.upsert_accounts_mechanical_invoice(
  p_reception_entry_id bigint,
  p_invoice_number text DEFAULT NULL,
  p_invoice_date date DEFAULT NULL,
  p_billed_amount numeric DEFAULT NULL,
  p_payment_status text DEFAULT NULL,
  p_amount_received numeric DEFAULT NULL,
  p_payment_notes text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_entry public.service_reception_entries%ROWTYPE;
  v_actor text;
  v_existing public.accounts_mechanical_invoices%ROWTYPE;
  v_has_lines boolean := false;
  v_invoice_number text;
  v_invoice_date date;
  v_billed numeric;
BEGIN
  IF NOT public.accounts_can_access() THEN
    RAISE EXCEPTION 'permission denied: requires accounts view'
      USING ERRCODE = '42501';
  END IF;

  SELECT * INTO v_entry
    FROM public.service_reception_entries
   WHERE id = p_reception_entry_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'reception entry % not found', p_reception_entry_id
      USING ERRCODE = 'P0002';
  END IF;
  IF v_entry.invoice_done_at IS NULL THEN
    RAISE EXCEPTION 'case is not Mark Done on Service Advisor'
      USING ERRCODE = '23514';
  END IF;
  IF NOT public.is_floor_incharge_service_type(v_entry.service_type) THEN
    RAISE EXCEPTION 'not a mechanical Floor Incharge service type'
      USING ERRCODE = '23514';
  END IF;
  IF NULLIF(btrim(v_entry.jc_number), '') IS NULL THEN
    RAISE EXCEPTION 'jc_number is required'
      USING ERRCODE = '23514';
  END IF;
  IF p_billed_amount IS NOT NULL AND p_billed_amount < 0 THEN
    RAISE EXCEPTION 'billed_amount cannot be negative'
      USING ERRCODE = '23514';
  END IF;

  -- Legacy args p_payment_status / p_amount_received are ignored. Status is derived.

  SELECT * INTO v_existing
    FROM public.accounts_mechanical_invoices
   WHERE reception_entry_id = p_reception_entry_id;

  IF FOUND THEN
    SELECT EXISTS (
      SELECT 1
      FROM public.accounts_mechanical_payment_lines l
      WHERE l.reception_entry_id = p_reception_entry_id
    ) INTO v_has_lines;
  END IF;

  IF v_has_lines THEN
    v_invoice_number := v_existing.invoice_number;
    v_invoice_date := v_existing.invoice_date;
    v_billed := v_existing.billed_amount;
  ELSE
    v_invoice_number := NULLIF(btrim(p_invoice_number), '');
    v_invoice_date := p_invoice_date;
    v_billed := CASE WHEN p_billed_amount IS NULL THEN NULL ELSE round(p_billed_amount, 2) END;
  END IF;

  v_actor := COALESCE(
    NULLIF(auth.jwt() ->> 'email', ''),
    NULLIF(auth.uid()::text, ''),
    'system'
  );

  INSERT INTO public.accounts_mechanical_invoices (
    reception_entry_id, jc_number, invoice_number, invoice_date, billed_amount,
    payment_status, amount_received, payment_notes, captured_by, captured_at, updated_at
  ) VALUES (
    p_reception_entry_id,
    btrim(v_entry.jc_number),
    v_invoice_number,
    v_invoice_date,
    v_billed,
    'pending',
    NULL,
    CASE
      WHEN v_has_lines THEN v_existing.payment_notes
      ELSE NULLIF(btrim(p_payment_notes), '')
    END,
    v_actor,
    now(),
    now()
  )
  ON CONFLICT (reception_entry_id) DO UPDATE SET
    jc_number = EXCLUDED.jc_number,
    invoice_number = EXCLUDED.invoice_number,
    invoice_date = EXCLUDED.invoice_date,
    billed_amount = EXCLUDED.billed_amount,
    payment_notes = EXCLUDED.payment_notes,
    updated_at = now();

  PERFORM public.accounts_mechanical_recalc(p_reception_entry_id);
  RETURN public.accounts_mechanical_case_json(p_reception_entry_id);
END;
$$;

-- ---------------------------------------------------------------------------
-- E. Post / list receipts
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.add_accounts_mechanical_payment(
  p_reception_entry_id bigint,
  p_amount numeric,
  p_payment_mode text,
  p_reference text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_inv public.accounts_mechanical_invoices%ROWTYPE;
  v_mode text;
  v_amount numeric;
  v_remaining numeric;
  v_actor text;
BEGIN
  IF NOT public.accounts_can_access() THEN
    RAISE EXCEPTION 'permission denied: requires accounts view'
      USING ERRCODE = '42501';
  END IF;

  SELECT * INTO v_inv
    FROM public.accounts_mechanical_invoices
   WHERE reception_entry_id = p_reception_entry_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'capture invoice number and billed amount first'
      USING ERRCODE = '23514';
  END IF;
  IF v_inv.billed_amount IS NULL THEN
    RAISE EXCEPTION 'billed amount is required before posting a receipt'
      USING ERRCODE = '23514';
  END IF;

  v_amount := round(COALESCE(p_amount, 0), 2);
  IF v_amount <= 0 THEN
    RAISE EXCEPTION 'receipt amount must be greater than 0'
      USING ERRCODE = '23514';
  END IF;

  v_mode := lower(btrim(COALESCE(p_payment_mode, '')));
  IF v_mode NOT IN ('cash', 'upi', 'card', 'cheque', 'bank', 'other') THEN
    RAISE EXCEPTION 'invalid payment_mode'
      USING ERRCODE = '23514';
  END IF;

  v_remaining := GREATEST(0, round(v_inv.billed_amount - COALESCE(v_inv.amount_received, 0), 2));
  IF v_amount > v_remaining THEN
    RAISE EXCEPTION 'receipt ₹% exceeds remaining ₹%', v_amount, v_remaining
      USING ERRCODE = '23514';
  END IF;

  v_actor := COALESCE(
    NULLIF(auth.jwt() ->> 'email', ''),
    NULLIF(auth.uid()::text, ''),
    'system'
  );

  INSERT INTO public.accounts_mechanical_payment_lines (
    reception_entry_id, mechanical_invoice_id, amount, payment_mode, reference, posted_by, posted_at
  ) VALUES (
    p_reception_entry_id,
    v_inv.id,
    v_amount,
    v_mode,
    NULLIF(btrim(p_reference), ''),
    v_actor,
    now()
  );

  PERFORM public.accounts_mechanical_recalc(p_reception_entry_id);
  RETURN public.accounts_mechanical_case_json(p_reception_entry_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.list_accounts_mechanical_payments(p_reception_entry_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
SET row_security TO 'off'
AS $$
DECLARE
  v_rows jsonb;
BEGIN
  IF NOT public.accounts_can_access() THEN
    RAISE EXCEPTION 'permission denied: requires accounts view'
      USING ERRCODE = '42501';
  END IF;

  SELECT COALESCE(
    jsonb_agg(to_jsonb(l) ORDER BY l.posted_at ASC, l.id ASC),
    '[]'::jsonb
  )
    INTO v_rows
    FROM public.accounts_mechanical_payment_lines l
   WHERE l.reception_entry_id = p_reception_entry_id;

  RETURN v_rows;
END;
$$;

GRANT EXECUTE ON FUNCTION public.accounts_mechanical_recalc(bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.accounts_mechanical_case_json(bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.list_accounts_mechanical_cases() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.upsert_accounts_mechanical_invoice(bigint, text, date, numeric, text, numeric, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.add_accounts_mechanical_payment(bigint, numeric, text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.list_accounts_mechanical_payments(bigint) TO authenticated, service_role;
