-- Admin-managed customer helpdesk / escalation contacts (mobile + web portal).
-- Customer reads: customer_list_helpdesk_contacts(session) only (anon has no table grant).
-- Staff CRUD: authenticated + settings module (or admin) via Settings UI.
-- Rollback:
--   DROP FUNCTION IF EXISTS public.customer_list_helpdesk_contacts(text);
--   DROP TABLE IF EXISTS public.settings_customer_helpdesk_contacts CASCADE;

CREATE TABLE IF NOT EXISTS public.settings_customer_helpdesk_contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_key text NOT NULL CHECK (group_key = ANY (ARRAY['dealership'::text, 'tata_motors'::text])),
  sort_order integer NOT NULL DEFAULT 0,
  level_label text NOT NULL,
  contact_name text NOT NULL,
  role_title text NOT NULL,
  description text,
  phone text NOT NULL,
  email text,
  icon_emoji text DEFAULT '👤'::text,
  badge_variant text NOT NULL DEFAULT 'blue'::text CHECK (
    badge_variant = ANY (ARRAY['blue'::text, 'amber'::text, 'rose'::text, 'indigo'::text, 'emerald'::text])
  ),
  chat_contact_key text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT settings_customer_helpdesk_contacts_chat_key_unique UNIQUE (chat_contact_key)
);

COMMENT ON TABLE public.settings_customer_helpdesk_contacts IS
  'Customer helpdesk / escalation matrix. Edited in Settings; mobile loads active rows via customer_list_helpdesk_contacts.';

CREATE INDEX IF NOT EXISTS idx_settings_customer_helpdesk_contacts_group_sort
  ON public.settings_customer_helpdesk_contacts (group_key, sort_order, id);

CREATE OR REPLACE FUNCTION public.settings_customer_helpdesk_contacts_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_settings_customer_helpdesk_contacts_updated_at ON public.settings_customer_helpdesk_contacts;
CREATE TRIGGER trg_settings_customer_helpdesk_contacts_updated_at
  BEFORE UPDATE ON public.settings_customer_helpdesk_contacts
  FOR EACH ROW
  EXECUTE FUNCTION public.settings_customer_helpdesk_contacts_touch_updated_at();

ALTER TABLE public.settings_customer_helpdesk_contacts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.settings_customer_helpdesk_contacts FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.settings_customer_helpdesk_contacts TO authenticated;
GRANT ALL ON TABLE public.settings_customer_helpdesk_contacts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.settings_customer_helpdesk_contacts_id_seq TO authenticated, service_role;

DROP POLICY IF EXISTS settings_customer_helpdesk_contacts_select_v1 ON public.settings_customer_helpdesk_contacts;
DROP POLICY IF EXISTS settings_customer_helpdesk_contacts_insert_v1 ON public.settings_customer_helpdesk_contacts;
DROP POLICY IF EXISTS settings_customer_helpdesk_contacts_update_v1 ON public.settings_customer_helpdesk_contacts;
DROP POLICY IF EXISTS settings_customer_helpdesk_contacts_delete_v1 ON public.settings_customer_helpdesk_contacts;

CREATE POLICY settings_customer_helpdesk_contacts_select_v1
  ON public.settings_customer_helpdesk_contacts
  FOR SELECT
  TO authenticated
  USING (public.is_admin() OR public.has_module_view('settings'::text));

CREATE POLICY settings_customer_helpdesk_contacts_insert_v1
  ON public.settings_customer_helpdesk_contacts
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin() OR public.has_module_view('settings'::text));

CREATE POLICY settings_customer_helpdesk_contacts_update_v1
  ON public.settings_customer_helpdesk_contacts
  FOR UPDATE
  TO authenticated
  USING (public.is_admin() OR public.has_module_view('settings'::text))
  WITH CHECK (public.is_admin() OR public.has_module_view('settings'::text));

CREATE POLICY settings_customer_helpdesk_contacts_delete_v1
  ON public.settings_customer_helpdesk_contacts
  FOR DELETE
  TO authenticated
  USING (public.is_admin() OR public.has_module_view('settings'::text));

-- Seed defaults (matches prior hardcoded mobile matrix).
INSERT INTO public.settings_customer_helpdesk_contacts (
  group_key, sort_order, level_label, contact_name, role_title, description, phone, email, icon_emoji, badge_variant, chat_contact_key
) VALUES
  (
    'dealership', 10, 'Level 1 · CRM Desk', 'Payal Makhija', 'Customer Relationship Manager (CRM)',
    'Vehicle service queries, appointment coordination, delay issues & prompt resolution.',
    '9116667296', 'Crmservice@techwheels.in', '👩‍💼', 'blue', 'payal'
  ),
  (
    'dealership', 20, 'Level 2 · Service Head', 'Govind Singh', 'Service Manager (Workshop Operations)',
    'Technical disputes, repair quality oversight & workshop floor management.',
    '9116667274', 'service@techwheels.in', '👨‍💼', 'amber', 'govind'
  ),
  (
    'dealership', 30, 'Level 3 · Dealership GM', 'Mr Rajesh Panday', 'General Manager (Dealership Head)',
    'Executive escalation, unresolved grievances, critical repeat issues & billing disputes.',
    '9257051606', 'gmservice@techwheels.in', '🏛️', 'rose', 'rajesh'
  ),
  (
    'tata_motors', 10, 'Tata Motors · Level 1', 'Mr Akshay Jethalia', 'Customer Care Manager (Tata Motors Official)',
    'Official Tata Motors OEM customer care, warranty policies & vehicle escalation.',
    '9328726988', 'AJJ820986@tatamotors.com', '🚘', 'indigo', 'tata_akshay'
  ),
  (
    'tata_motors', 20, 'Tata Motors · Regional Head', 'Mr Gurmeet Singh', 'Regional Customer Care Manager (Tata Motors Official)',
    'Regional OEM leadership intervention for state-level unresolved customer complaints.',
    '8288004301', 'gumeet.singh@tatamotors.com', '🌐', 'emerald', 'tata_gurmeet'
  )
ON CONFLICT (chat_contact_key) DO NOTHING;

CREATE OR REPLACE FUNCTION public.customer_list_helpdesk_contacts(p_session_token text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO public, extensions
AS $$
BEGIN
  PERFORM public.customer_require_session(p_session_token);

  RETURN COALESCE(
    (
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', c.id,
          'group_key', c.group_key,
          'sort_order', c.sort_order,
          'level_label', c.level_label,
          'contact_name', c.contact_name,
          'role_title', c.role_title,
          'description', c.description,
          'phone', c.phone,
          'email', c.email,
          'icon_emoji', c.icon_emoji,
          'badge_variant', c.badge_variant,
          'chat_contact_key', c.chat_contact_key
        )
        ORDER BY c.group_key, c.sort_order, c.id
      )
      FROM public.settings_customer_helpdesk_contacts c
      WHERE c.is_active = true
    ),
    '[]'::jsonb
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.customer_helpdesk_peer_name(p_contact_key text, p_default_sa text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (
      SELECT c.contact_name
      FROM public.settings_customer_helpdesk_contacts c
      WHERE c.is_active = true
        AND c.chat_contact_key = btrim(COALESCE(p_contact_key, ''))
      LIMIT 1
    ),
    CASE btrim(COALESCE(p_contact_key, 'advisor'))
      WHEN 'payal' THEN 'Payal Makhija'
      WHEN 'govind' THEN 'Govind Singh'
      WHEN 'rajesh' THEN 'Mr Rajesh Panday'
      WHEN 'tata_akshay' THEN 'Mr Akshay Jethalia'
      WHEN 'tata_gurmeet' THEN 'Mr Gurmeet Singh'
      ELSE COALESCE(NULLIF(btrim(p_default_sa), ''), 'Service advisor')
    END
  );
$$;

REVOKE ALL ON FUNCTION public.customer_list_helpdesk_contacts(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.customer_list_helpdesk_contacts(text) TO anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.customer_helpdesk_peer_name(text, text) FROM PUBLIC;
