-- Migration: Add support-person assignments for Floor Incharge job cards
-- Purpose:
-- 1) Allow one active additional person assignment per job card.
-- 2) Support role-based assignment from employee_master (DET/ELECTRICIAN/DENTER/TECHNICIAN).
-- 3) Keep RLS semantics aligned with floor_incharge module permissions.

BEGIN;

CREATE TABLE IF NOT EXISTS public.job_card_support_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_card_number text NOT NULL,
  support_role text NOT NULL,
  employee_code text NOT NULL,
  employee_name text NOT NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  assigned_by text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'job_card_support_assignments_support_role_check'
      AND conrelid = 'public.job_card_support_assignments'::regclass
  ) THEN
    ALTER TABLE public.job_card_support_assignments
      ADD CONSTRAINT job_card_support_assignments_support_role_check
      CHECK (upper(btrim(support_role)) IN ('DET', 'ELECTRICIAN', 'DENTER', 'TECHNICIAN'));
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.normalize_job_card_support_assignment()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.job_card_number := upper(btrim(coalesce(NEW.job_card_number, '')));
  NEW.support_role := upper(btrim(coalesce(NEW.support_role, '')));
  NEW.employee_code := upper(btrim(coalesce(NEW.employee_code, '')));
  NEW.employee_name := btrim(coalesce(NEW.employee_name, ''));

  IF NEW.job_card_number = '' THEN
    RAISE EXCEPTION 'job_card_number is required';
  END IF;

  IF NEW.employee_code = '' THEN
    RAISE EXCEPTION 'employee_code is required';
  END IF;

  IF NEW.employee_name = '' THEN
    RAISE EXCEPTION 'employee_name is required';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_job_card_support_assignments_normalize ON public.job_card_support_assignments;
CREATE TRIGGER trg_job_card_support_assignments_normalize
  BEFORE INSERT OR UPDATE ON public.job_card_support_assignments
  FOR EACH ROW EXECUTE FUNCTION public.normalize_job_card_support_assignment();

DROP TRIGGER IF EXISTS trg_job_card_support_assignments_updated_at ON public.job_card_support_assignments;
CREATE TRIGGER trg_job_card_support_assignments_updated_at
  BEFORE UPDATE ON public.job_card_support_assignments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX IF NOT EXISTS idx_job_card_support_assignments_job_card
  ON public.job_card_support_assignments (job_card_number);

CREATE INDEX IF NOT EXISTS idx_job_card_support_assignments_role
  ON public.job_card_support_assignments (support_role);

CREATE INDEX IF NOT EXISTS idx_job_card_support_assignments_employee_code
  ON public.job_card_support_assignments (employee_code);

CREATE INDEX IF NOT EXISTS idx_job_card_support_assignments_is_active
  ON public.job_card_support_assignments (is_active);

DROP INDEX IF EXISTS public.uq_job_card_support_assignments_active_job_card;

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_card_support_assignments_active_job_card_employee
  ON public.job_card_support_assignments ((upper(btrim(job_card_number))), (upper(btrim(employee_code))))
  WHERE is_active;

ALTER TABLE public.job_card_support_assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS job_card_support_assignments_select_rbac ON public.job_card_support_assignments;
DROP POLICY IF EXISTS job_card_support_assignments_insert_rbac ON public.job_card_support_assignments;
DROP POLICY IF EXISTS job_card_support_assignments_update_rbac ON public.job_card_support_assignments;
DROP POLICY IF EXISTS job_card_support_assignments_delete_rbac ON public.job_card_support_assignments;

CREATE POLICY job_card_support_assignments_select_rbac ON public.job_card_support_assignments
  FOR SELECT TO authenticated
  USING (public.is_admin() OR public.has_module_view('floor_incharge'));

CREATE POLICY job_card_support_assignments_insert_rbac ON public.job_card_support_assignments
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin() OR public.has_module_modify('floor_incharge'));

CREATE POLICY job_card_support_assignments_update_rbac ON public.job_card_support_assignments
  FOR UPDATE TO authenticated
  USING (public.is_admin() OR public.has_module_modify('floor_incharge'))
  WITH CHECK (public.is_admin() OR public.has_module_modify('floor_incharge'));

CREATE POLICY job_card_support_assignments_delete_rbac ON public.job_card_support_assignments
  FOR DELETE TO authenticated
  USING (public.is_admin() OR public.has_module_delete('floor_incharge'));

COMMENT ON TABLE public.job_card_support_assignments IS
  'Stores one active support-person assignment per job card for floor incharge workflow.';

COMMENT ON COLUMN public.job_card_support_assignments.support_role IS
  'Allowed roles: DET, ELECTRICIAN, DENTER, TECHNICIAN.';

COMMENT ON COLUMN public.job_card_support_assignments.is_active IS
  'Soft-active flag. Allows multiple active support assignments per job card.';

COMMIT;
