-- Per-role self QC from Floor Work (Dentor / Painter / Technician). RI when all pass + pipeline done.

CREATE TABLE IF NOT EXISTS public.bodyshop_floor_worker_role_qc (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_card_number text NOT NULL,
  repair_card_id bigint NOT NULL REFERENCES public.bodyshop_repair_cards (id) ON DELETE CASCADE,
  dealer_code text NOT NULL,
  floor_role text NOT NULL,
  employee_code text NOT NULL,
  qc_status text NOT NULL DEFAULT 'pending',
  fail_reason text,
  checked_by_name text,
  checked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bodyshop_floor_worker_role_qc_role_check CHECK (
    floor_role = ANY (ARRAY['DENTOR'::text, 'PAINTER'::text, 'TECHNICIAN'::text])
  ),
  CONSTRAINT bodyshop_floor_worker_role_qc_status_check CHECK (
    qc_status = ANY (ARRAY['pending'::text, 'pass'::text, 'fail'::text])
  ),
  CONSTRAINT bodyshop_floor_worker_role_qc_jc_role_key UNIQUE (job_card_number, floor_role)
);

CREATE INDEX IF NOT EXISTS bodyshop_floor_worker_role_qc_repair_card_idx
  ON public.bodyshop_floor_worker_role_qc (repair_card_id);

COMMENT ON TABLE public.bodyshop_floor_worker_role_qc IS
  'Floor Work: each primary worker (Dentor/Painter/Technician) Pass/Fail after their step is Done.';

CREATE OR REPLACE FUNCTION public.touch_bodyshop_floor_worker_role_qc_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS bodyshop_floor_worker_role_qc_updated_at ON public.bodyshop_floor_worker_role_qc;
CREATE TRIGGER bodyshop_floor_worker_role_qc_updated_at
  BEFORE UPDATE ON public.bodyshop_floor_worker_role_qc
  FOR EACH ROW EXECUTE FUNCTION public.touch_bodyshop_floor_worker_role_qc_updated_at();

ALTER TABLE public.bodyshop_floor_worker_role_qc ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bodyshop_floor_worker_role_qc_admin_all ON public.bodyshop_floor_worker_role_qc;
CREATE POLICY bodyshop_floor_worker_role_qc_admin_all
  ON public.bodyshop_floor_worker_role_qc
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS bodyshop_floor_worker_role_qc_select ON public.bodyshop_floor_worker_role_qc;
CREATE POLICY bodyshop_floor_worker_role_qc_select
  ON public.bodyshop_floor_worker_role_qc
  FOR SELECT
  TO authenticated
  USING (
    public.is_admin()
    OR (
      public.dealer_code_in_scope(dealer_code)
      AND (
        public.has_module_view('bodyshop_floor_work')
        OR public.has_module_modify('bodyshop_floor_work')
        OR public.has_module_view('bodyshop_floor')
        OR public.has_module_modify('bodyshop_floor')
      )
    )
  );

DROP POLICY IF EXISTS bodyshop_floor_worker_role_qc_upsert_worker ON public.bodyshop_floor_worker_role_qc;
CREATE POLICY bodyshop_floor_worker_role_qc_upsert_worker
  ON public.bodyshop_floor_worker_role_qc
  FOR ALL
  TO authenticated
  USING (
    public.is_admin()
    OR (
      public.has_module_modify('bodyshop_floor_work')
      AND public.dealer_code_in_scope(dealer_code)
      AND upper(btrim(employee_code)) = upper(btrim(public.my_employee_code()))
    )
  )
  WITH CHECK (
    public.is_admin()
    OR (
      public.has_module_modify('bodyshop_floor_work')
      AND public.dealer_code_in_scope(dealer_code)
      AND upper(btrim(employee_code)) = upper(btrim(public.my_employee_code()))
    )
  );

GRANT SELECT, INSERT, UPDATE ON public.bodyshop_floor_worker_role_qc TO authenticated;
